In [1]:
import numpy as np

image = np.load("image_data_per_episode.npy")

velocity = np.load("velocity_data_per_episode.npy")

episode = np.load("episode_length.npy")

In [2]:
episode = np.load("episode_length.npy")
episode

array([  37,   92,  145,  204,  275,  329,  386,  437,  503,  555,  606,
        647,  692,  750,  790,  832,  858,  894,  933,  971, 1006, 1041,
       1075, 1106, 1140, 1174, 1201, 1229, 1261, 1287, 1319, 1344, 1370,
       1390, 1424, 1448, 1467, 1491, 1515, 1539, 1562, 1588, 1614, 1637,
       1659, 1678, 1702, 1723, 1744, 1761, 1779, 1800, 1819, 1838, 1857,
       1874, 1890, 1908, 1923, 1944, 1968, 1988, 2009, 2031, 2054, 2073,
       2090, 2107, 2132, 2151, 2175, 2194, 2212, 2232, 2253, 2271, 2293,
       2313, 2328, 2343, 2364, 2380, 2415, 2446, 2463, 2491, 2506, 2522,
       2536, 2551, 2568, 2587, 2604, 2623, 2638, 2656, 2672, 2691, 2709,
       2737,   44,  105,  167,  220,  295,  366,  430,  507,  566,  625,
        684,  740,  787,  851,  914,  973, 1024, 1092, 1130, 1187, 1230,
       1267, 1306, 1332, 1385, 1423, 1452, 1487, 1527, 1554, 1580, 1618,
       1639, 1674, 1697, 1727, 1757, 1780, 1806, 1838, 1870, 1898, 1933,
       1959, 1989, 2017, 2045, 2070, 2092, 2115, 21

In [2]:
episode.shape

(800,)

In [4]:

for i in range(1,8):
    for j in range(0,100):
        print(f'{episode[100*i -1]} + {episode[100*i + j]} = {episode[100*i + j] + episode[100*i -1]}')
        episode[100*i + j] = episode[100*i -1] + episode[100*i + j]

2737 + 44 = 2781
2737 + 105 = 2842
2737 + 167 = 2904
2737 + 220 = 2957
2737 + 295 = 3032
2737 + 366 = 3103
2737 + 430 = 3167
2737 + 507 = 3244
2737 + 566 = 3303
2737 + 625 = 3362
2737 + 684 = 3421
2737 + 740 = 3477
2737 + 787 = 3524
2737 + 851 = 3588
2737 + 914 = 3651
2737 + 973 = 3710
2737 + 1024 = 3761
2737 + 1092 = 3829
2737 + 1130 = 3867
2737 + 1187 = 3924
2737 + 1230 = 3967
2737 + 1267 = 4004
2737 + 1306 = 4043
2737 + 1332 = 4069
2737 + 1385 = 4122
2737 + 1423 = 4160
2737 + 1452 = 4189
2737 + 1487 = 4224
2737 + 1527 = 4264
2737 + 1554 = 4291
2737 + 1580 = 4317
2737 + 1618 = 4355
2737 + 1639 = 4376
2737 + 1674 = 4411
2737 + 1697 = 4434
2737 + 1727 = 4464
2737 + 1757 = 4494
2737 + 1780 = 4517
2737 + 1806 = 4543
2737 + 1838 = 4575
2737 + 1870 = 4607
2737 + 1898 = 4635
2737 + 1933 = 4670
2737 + 1959 = 4696
2737 + 1989 = 4726
2737 + 2017 = 4754
2737 + 2045 = 4782
2737 + 2070 = 4807
2737 + 2092 = 4829
2737 + 2115 = 4852
2737 + 2144 = 4881
2737 + 2168 = 4905
2737 + 2192 = 4929
2737 + 221

In [2]:
image.shape

(27074, 160, 120, 3)

In [3]:
episode

array([  115.,   234.,   405.,   535.,   656.,   821.,   878.,   951.,
        1033.,  1149.,  1200.,  1259.,  1300.,  1347.,  1407.,  1454.,
        1497.,  1551.,  1614.,  1685.,  1719.,  1750.,  1774.,  1806.,
        1836.,  1874.,  1918.,  1956.,  1992.,  2020.,  2061.,  2082.,
        2120.,  2154.,  2178.,  2204.,  2231.,  2262.,  2289.,  2313.,
        2342.,  2375.,  2401.,  2441.,  2468.,  2508.,  2525.,  2551.,
        2588.,  2616.,  2646.,  2689.,  2713.,  2749.,  2794.,  2839.,
        2862.,  2891.,  2913.,  2943.,  2964.,  3001.,  3024.,  3045.,
        3069.,  3091.,  3118.,  3136.,  3160.,  3179.,  3207.,  3228.,
        3247.,  3268.,  3284.,  3307.,  3324.,  3339.,  3354.,  3369.,
        3393.,  3414.,  3433.,  3453.,  3469.,  3484.,  3504.,  3526.,
        3545.,  3564.,  3580.,  3595.,  3616.,  3635.,  3654.,  3669.,
        3686.,  3710.,  3725.,  3741.,  3808.,  3875.,  4042.,  4122.,
        4198.,  4493.,  4580.,  4649.,  4734.,  4810.,  4902.,  4953.,
      

In [7]:
np.array_equal(image[2737], np.zeros([160,120,3]))

True

In [8]:
episode[199] = 6029

In [9]:
episode[299] = 9360

In [10]:
episode[199]

6029

In [4]:
for i in range(26886):
    if np.array_equal(image[i], np.zeros([160,120,3])):
        print(i)

In [93]:
import cv2

im = image[12937]
cv2.imwrite('image.png',im)

True

In [12]:
element_to_add_1 = -1*np.ones([800,])
element_to_add_2 = np.append(np.zeros(99),-1*np.ones([701,]))
element_to_add_3 = np.append(np.zeros(199),-1*np.ones([601,]))
element_to_add_4 = np.append(np.zeros(299),-1*np.ones([501,]))
element_to_add_5 = np.append(np.zeros(399),-1*np.ones([401,]))
element_to_add_6 = np.append(np.zeros(499),-1*np.ones([301,]))
element_to_add_7 = np.append(np.zeros(599),-1*np.ones([201,]))
element_to_add_8 = np.append(np.zeros(699),-1*np.ones([101,]))
element_to_add = [element_to_add_1,element_to_add_1,element_to_add_2,element_to_add_3,element_to_add_4,
                 element_to_add_5,element_to_add_6,element_to_add_7,element_to_add_8]

image_to_delete = [0,0,3742,7595,11099,14601,17779,20639,23925]

In [13]:
episode[99]

2737

In [14]:
for image_to,element_to in zip(image_to_delete,element_to_add):
    image = np.delete(image,[image_to],axis=0)

    print('********before********')
    print(episode)
    episode = np.add(episode,element_to)
    print('********after********')
    print(episode)

********before********
[   37    92   145   204   275   329   386   437   503   555   606   647
   692   750   790   832   858   894   933   971  1006  1041  1075  1106
  1140  1174  1201  1229  1261  1287  1319  1344  1370  1390  1424  1448
  1467  1491  1515  1539  1562  1588  1614  1637  1659  1678  1702  1723
  1744  1761  1779  1800  1819  1838  1857  1874  1890  1908  1923  1944
  1968  1988  2009  2031  2054  2073  2090  2107  2132  2151  2175  2194
  2212  2232  2253  2271  2293  2313  2328  2343  2364  2380  2415  2446
  2463  2491  2506  2522  2536  2551  2568  2587  2604  2623  2638  2656
  2672  2691  2709  2737  2781  2842  2904  2957  3032  3103  3167  3244
  3303  3362  3421  3477  3524  3588  3651  3710  3761  3829  3867  3924
  3967  4004  4043  4069  4122  4160  4189  4224  4264  4291  4317  4355
  4376  4411  4434  4464  4494  4517  4543  4575  4607  4635  4670  4696
  4726  4754  4782  4807  4829  4852  4881  4905  4929  4954  4979  5009
  5038  5064  5089  5112  51

********before********
[   36.    91.   144.   203.   274.   328.   385.   436.   502.   554.
   605.   646.   691.   749.   789.   831.   857.   893.   932.   970.
  1005.  1040.  1074.  1105.  1139.  1173.  1200.  1228.  1260.  1286.
  1318.  1343.  1369.  1389.  1423.  1447.  1466.  1490.  1514.  1538.
  1561.  1587.  1613.  1636.  1658.  1677.  1701.  1722.  1743.  1760.
  1778.  1799.  1818.  1837.  1856.  1873.  1889.  1907.  1922.  1943.
  1967.  1987.  2008.  2030.  2053.  2072.  2089.  2106.  2131.  2150.
  2174.  2193.  2211.  2231.  2252.  2270.  2292.  2312.  2327.  2342.
  2363.  2379.  2414.  2445.  2462.  2490.  2505.  2521.  2535.  2550.
  2567.  2586.  2603.  2622.  2637.  2655.  2671.  2690.  2708.  2736.
  2780.  2841.  2903.  2956.  3031.  3102.  3166.  3243.  3302.  3361.
  3420.  3476.  3523.  3587.  3650.  3709.  3760.  3828.  3866.  3923.
  3966.  4003.  4042.  4068.  4121.  4159.  4188.  4223.  4263.  4290.
  4316.  4354.  4375.  4410.  4433.  4463.  4493.  451

********before********
[   36.    91.   144.   203.   274.   328.   385.   436.   502.   554.
   605.   646.   691.   749.   789.   831.   857.   893.   932.   970.
  1005.  1040.  1074.  1105.  1139.  1173.  1200.  1228.  1260.  1286.
  1318.  1343.  1369.  1389.  1423.  1447.  1466.  1490.  1514.  1538.
  1561.  1587.  1613.  1636.  1658.  1677.  1701.  1722.  1743.  1760.
  1778.  1799.  1818.  1837.  1856.  1873.  1889.  1907.  1922.  1943.
  1967.  1987.  2008.  2030.  2053.  2072.  2089.  2106.  2131.  2150.
  2174.  2193.  2211.  2231.  2252.  2270.  2292.  2312.  2327.  2342.
  2363.  2379.  2414.  2445.  2462.  2490.  2505.  2521.  2535.  2550.
  2567.  2586.  2603.  2622.  2637.  2655.  2671.  2690.  2708.  2735.
  2779.  2840.  2902.  2955.  3030.  3101.  3165.  3242.  3301.  3360.
  3419.  3475.  3522.  3586.  3649.  3708.  3759.  3827.  3865.  3922.
  3965.  4002.  4041.  4067.  4120.  4158.  4187.  4222.  4262.  4289.
  4315.  4353.  4374.  4409.  4432.  4462.  4492.  451

********before********
[   36.    91.   144.   203.   274.   328.   385.   436.   502.   554.
   605.   646.   691.   749.   789.   831.   857.   893.   932.   970.
  1005.  1040.  1074.  1105.  1139.  1173.  1200.  1228.  1260.  1286.
  1318.  1343.  1369.  1389.  1423.  1447.  1466.  1490.  1514.  1538.
  1561.  1587.  1613.  1636.  1658.  1677.  1701.  1722.  1743.  1760.
  1778.  1799.  1818.  1837.  1856.  1873.  1889.  1907.  1922.  1943.
  1967.  1987.  2008.  2030.  2053.  2072.  2089.  2106.  2131.  2150.
  2174.  2193.  2211.  2231.  2252.  2270.  2292.  2312.  2327.  2342.
  2363.  2379.  2414.  2445.  2462.  2490.  2505.  2521.  2535.  2550.
  2567.  2586.  2603.  2622.  2637.  2655.  2671.  2690.  2708.  2735.
  2779.  2840.  2902.  2955.  3030.  3101.  3165.  3242.  3301.  3360.
  3419.  3475.  3522.  3586.  3649.  3708.  3759.  3827.  3865.  3922.
  3965.  4002.  4041.  4067.  4120.  4158.  4187.  4222.  4262.  4289.
  4315.  4353.  4374.  4409.  4432.  4462.  4492.  451

ValueError: operands could not be broadcast together with shapes (800,) (900,) 

In [17]:
np.array_equal(image[0], np.zeros([160,120,3]))

True

In [5]:
image.shape

(27074, 160, 120, 3)

In [14]:
print(f'99 ==> {episode[99]}')
print(f'100 ==> {episode[100]}')
print(f'199 ==> {episode[199]}')
print(f'200 ==> {episode[200]}')
print(f'299 ==> {episode[299]}')
print(f'300 ==> {episode[300]}')
print(f'399 ==> {episode[399]}')
print(f'400 ==> {episode[400]}')
print(f'499 ==> {episode[499]}')
print(f'500 ==> {episode[500]}')
print(f'599 ==> {episode[599]}')
print(f'600 ==> {episode[600]}')
print(f'699 ==> {episode[699]}')
print(f'700 ==> {episode[700]}')
print(f'799 ==> {episode[799]}')

99 ==> 3741.0
100 ==> 3808.0
199 ==> 7592.0
200 ==> 7651.0
299 ==> 11098.0
300 ==> 11153.0
399 ==> 14602.0
400 ==> 14672.0
499 ==> 17778.0
500 ==> 17850.0
599 ==> 20638.0
600 ==> 20714.0
699 ==> 23924.0
700 ==> 24013.0
799 ==> 27074.0


# Delete first episode data in each map

In [3]:
episode

array([  115.,   234.,   405.,   535.,   656.,   821.,   878.,   951.,
        1033.,  1149.,  1200.,  1259.,  1300.,  1347.,  1407.,  1454.,
        1497.,  1551.,  1614.,  1685.,  1719.,  1750.,  1774.,  1806.,
        1836.,  1874.,  1918.,  1956.,  1992.,  2020.,  2061.,  2082.,
        2120.,  2154.,  2178.,  2204.,  2231.,  2262.,  2289.,  2313.,
        2342.,  2375.,  2401.,  2441.,  2468.,  2508.,  2525.,  2551.,
        2588.,  2616.,  2646.,  2689.,  2713.,  2749.,  2794.,  2839.,
        2862.,  2891.,  2913.,  2943.,  2964.,  3001.,  3024.,  3045.,
        3069.,  3091.,  3118.,  3136.,  3160.,  3179.,  3207.,  3228.,
        3247.,  3268.,  3284.,  3307.,  3324.,  3339.,  3354.,  3369.,
        3393.,  3414.,  3433.,  3453.,  3469.,  3484.,  3504.,  3526.,
        3545.,  3564.,  3580.,  3595.,  3616.,  3635.,  3654.,  3669.,
        3686.,  3710.,  3725.,  3741.,  3808.,  3875.,  4042.,  4122.,
        4198.,  4493.,  4580.,  4649.,  4734.,  4810.,  4902.,  4953.,
      

In [4]:
to_delete = [
    [i for i in range(0,int(episode[0]))],
    [i for i in range(int(episode[99]),int(episode[100]))],
    [i for i in range(int(episode[199]),int(episode[200]))],
    [i for i in range(int(episode[299]),int(episode[300]))],
    [i for i in range(int(episode[399]),int(episode[400]))],
    [i for i in range(int(episode[499]),int(episode[500]))],
    [i for i in range(int(episode[599]),int(episode[600]))],
    [i for i in range(int(episode[699]),int(episode[700]))],
]
to_delete_unpacked = []

for i in to_delete:
    for j in i:
        to_delete_unpacked.append(j)

len(to_delete_unpacked)

603

In [5]:
length_of_episode_deleted = [115.0,
                            episode[100]-episode[99],
                            episode[200]-episode[199],
                             episode[300]-episode[299],
                             episode[400]-episode[399],
                             episode[500]-episode[499],
                             episode[600]-episode[599],
                             episode[700]-episode[699],
                            ]
length_of_episode_deleted

[115.0, 67.0, 59.0, 55.0, 70.0, 72.0, 76.0, 89.0]

In [ ]:
image = np.delete(image,to_delete_unpacked,axis=0)
velocity = np.delete(velocity,to_delete_unpacked,axis=0)

#delete episode lengths

#np.delete(episode,[0],axis=0)
element_to_add_1 = -115*np.ones([799,])

#np.delete(episode,[99],axis=0)
element_to_add_2 = np.append(np.zeros(99),-67*np.ones([699,]))

#np.delete(episode,[198],axis=0)
element_to_add_3 = np.append(np.zeros(198),-59*np.ones([599,]))

#np.delete(episode,[297],axis=0)
element_to_add_4 = np.append(np.zeros(297),-55*np.ones([499,]))

#np.delete(episode,[396],axis=0)
element_to_add_5 = np.append(np.zeros(396),-70*np.ones([399,]))

#np.delete(episode,[495],axis=0)
element_to_add_6 = np.append(np.zeros(495),-72*np.ones([299,]))

#np.delete(episode,[594],axis=0)
element_to_add_7 = np.append(np.zeros(594),-76*np.ones([199,]))

#np.delete(episode,[693],axis=0)
element_to_add_8 = np.append(np.zeros(693),-89*np.ones([99,]))

element_to_add = [element_to_add_1,element_to_add_2,element_to_add_3,element_to_add_4,
                 element_to_add_5,element_to_add_6,element_to_add_7,element_to_add_8]

for element_to,episodeioo in zip(element_to_add,[0,99,198,297,396,495,594,693]):
    
    print('********before********')
    print(episode.shape)
    print(element_to.shape)
    episode = np.delete(episode,[episodeioo],axis=0)
    episode = np.add(episode,element_to)
    print('********after********')
    print(episode.shape)
    print(element_to.shape)
    