In [1]:
ls

 12740.jpg
 12741.jpg
 16083.jpg
 16084.jpg
 19254.jpg
 19255.jpg
 22280.jpg
 22281.jpg
 3129.jpg
 3130.jpg
 6453.jpg
 6454.jpg
 9833.jpg
 9834.jpg
 basic_marker.py*
 chatGPT_recommended.py*
 contact.py*
 current_goal_pose_subscriber.py*
 current_pose.npy
 current_pose_per_episode.npy
'Data Cleaning.ipynb'
'Data Cleaning second try.ipynb'*
 episode_length.npy*
 hossein_jooon2.py*
 hossein_jooon.py*
 hossein_jooon_read_image_insideloop.py*
 image_data.npy*
 image_data_per_episode_first_deleted.npy
 image_data_per_episode.npy*
 image_subscriber.py*
 image_vel_subscriber.py*
 kir_to_hossein.jpg
 kir_to_hossein.png
 model2.py*
 my_robot_controller.py*
 pose_orien_data.npy*
 reset.py*
 rosmsg
 R_theta_data_fixed.npy
 R_theta_data.npy
 r_theta.ipynb
 temporary.py*
 test_episode_length.npy*
 test_image_data.npy*
 test_pose_orien_data.npy*
 test.py*
 test_velocity_data.npy*
 train_final.py*
 train_model.py
 velocity_data.npy*
 velocity_data_per_episode_first_deleted.npy
 velocity_data_per_epis

In [2]:
import numpy as np

image = np.load("image_data_per_episode.npy")

velocity = np.load("velocity_data_per_episode.npy")

#episode = np.load("episode_length.npy")

In [3]:
episode = np.load("episode_length.npy")
episode

array([   0,    1,   41,   85,  138,  205,  274,  349,  410,  469,  514,
        570,  632,  688,  739,  788,  843,  894,  947,  982, 1021, 1057,
       1099, 1150, 1198, 1253, 1295, 1333, 1359, 1393, 1425, 1460, 1497,
       1530, 1569, 1607, 1634, 1663, 1689, 1717, 1748, 1772, 1798, 1829,
       1855, 1884, 1916, 1958, 1988, 2017, 2042, 2064, 2088, 2107, 2125,
       2144, 2161, 2186, 2216, 2243, 2265, 2291, 2318, 2347, 2374, 2401,
       2423, 2450, 2467, 2484, 2508, 2529, 2554, 2575, 2598, 2618, 2637,
       2660, 2682, 2704, 2724, 2742, 2758, 2780, 2799, 2820, 2843, 2865,
       2886, 2911, 2933, 2954, 2977, 2995, 3013, 3034, 3059, 3077, 3094,
       3113, 3132,    1,   44,  115,  182,  250,  334,  410,  463,  546,
        623,  688,  739,  796,  841,  888,  931,  971, 1021, 1063, 1106,
       1146, 1191, 1237, 1275, 1330, 1375, 1416, 1450, 1480, 1510, 1560,
       1607, 1640, 1676, 1717, 1762, 1790, 1837, 1859, 1886, 1911, 1935,
       1962, 1991, 2029, 2067, 2099, 2129, 2162, 21

# Episode cleaning

In [4]:
episode = np.delete(episode,0)
episode

array([   1,   41,   85,  138,  205,  274,  349,  410,  469,  514,  570,
        632,  688,  739,  788,  843,  894,  947,  982, 1021, 1057, 1099,
       1150, 1198, 1253, 1295, 1333, 1359, 1393, 1425, 1460, 1497, 1530,
       1569, 1607, 1634, 1663, 1689, 1717, 1748, 1772, 1798, 1829, 1855,
       1884, 1916, 1958, 1988, 2017, 2042, 2064, 2088, 2107, 2125, 2144,
       2161, 2186, 2216, 2243, 2265, 2291, 2318, 2347, 2374, 2401, 2423,
       2450, 2467, 2484, 2508, 2529, 2554, 2575, 2598, 2618, 2637, 2660,
       2682, 2704, 2724, 2742, 2758, 2780, 2799, 2820, 2843, 2865, 2886,
       2911, 2933, 2954, 2977, 2995, 3013, 3034, 3059, 3077, 3094, 3113,
       3132,    1,   44,  115,  182,  250,  334,  410,  463,  546,  623,
        688,  739,  796,  841,  888,  931,  971, 1021, 1063, 1106, 1146,
       1191, 1237, 1275, 1330, 1375, 1416, 1450, 1480, 1510, 1560, 1607,
       1640, 1676, 1717, 1762, 1790, 1837, 1859, 1886, 1911, 1935, 1962,
       1991, 2029, 2067, 2099, 2129, 2162, 2192, 22

In [5]:

element_to_add = np.append(-1*np.ones([500,]),np.zeros([100]))
element_to_add = np.append(element_to_add,-1*np.ones([200,]))


element_to_delete = [0,100,200,300,400,600,700]

#Episode = np.add(episode,element_to_add)
Episode = np.delete(episode,element_to_delete)
Episode

array([  41,   85,  138,  205,  274,  349,  410,  469,  514,  570,  632,
        688,  739,  788,  843,  894,  947,  982, 1021, 1057, 1099, 1150,
       1198, 1253, 1295, 1333, 1359, 1393, 1425, 1460, 1497, 1530, 1569,
       1607, 1634, 1663, 1689, 1717, 1748, 1772, 1798, 1829, 1855, 1884,
       1916, 1958, 1988, 2017, 2042, 2064, 2088, 2107, 2125, 2144, 2161,
       2186, 2216, 2243, 2265, 2291, 2318, 2347, 2374, 2401, 2423, 2450,
       2467, 2484, 2508, 2529, 2554, 2575, 2598, 2618, 2637, 2660, 2682,
       2704, 2724, 2742, 2758, 2780, 2799, 2820, 2843, 2865, 2886, 2911,
       2933, 2954, 2977, 2995, 3013, 3034, 3059, 3077, 3094, 3113, 3132,
         44,  115,  182,  250,  334,  410,  463,  546,  623,  688,  739,
        796,  841,  888,  931,  971, 1021, 1063, 1106, 1146, 1191, 1237,
       1275, 1330, 1375, 1416, 1450, 1480, 1510, 1560, 1607, 1640, 1676,
       1717, 1762, 1790, 1837, 1859, 1886, 1911, 1935, 1962, 1991, 2029,
       2067, 2099, 2129, 2162, 2192, 2213, 2247, 22

In [6]:
# minus one ==> because of first image in each map which is a zero matrix
element_to_add = -1*np.ones(793)
Episode = np.add(Episode,element_to_add)


In [7]:
Episode

array([  40.,   84.,  137.,  204.,  273.,  348.,  409.,  468.,  513.,
        569.,  631.,  687.,  738.,  787.,  842.,  893.,  946.,  981.,
       1020., 1056., 1098., 1149., 1197., 1252., 1294., 1332., 1358.,
       1392., 1424., 1459., 1496., 1529., 1568., 1606., 1633., 1662.,
       1688., 1716., 1747., 1771., 1797., 1828., 1854., 1883., 1915.,
       1957., 1987., 2016., 2041., 2063., 2087., 2106., 2124., 2143.,
       2160., 2185., 2215., 2242., 2264., 2290., 2317., 2346., 2373.,
       2400., 2422., 2449., 2466., 2483., 2507., 2528., 2553., 2574.,
       2597., 2617., 2636., 2659., 2681., 2703., 2723., 2741., 2757.,
       2779., 2798., 2819., 2842., 2864., 2885., 2910., 2932., 2953.,
       2976., 2994., 3012., 3033., 3058., 3076., 3093., 3112., 3131.,
         43.,  114.,  181.,  249.,  333.,  409.,  462.,  545.,  622.,
        687.,  738.,  795.,  840.,  887.,  930.,  970., 1020., 1062.,
       1105., 1145., 1190., 1236., 1274., 1329., 1374., 1415., 1449.,
       1479., 1509.,

In [8]:
episode.shape

(800,)

# Let's continue

In [9]:
episode[499]

3344

In [10]:
q=0
for i in range(1,8):
    
    if i == 5:
        q=1
        for j in range(0,100):
            print(f'{Episode[99*i -1]} + {Episode[99*i + j]} = {Episode[99*i + j] + Episode[99*i -1]}')
            Episode[99*i + j] = Episode[99*i -1] + Episode[99*i + j]
    else:
        for j in range(0,99):
            print(f'{Episode[99*i -1+q]} + {Episode[99*i + j+q]} = {Episode[99*i + j+q] + Episode[99*i -1+q]}')
            Episode[99*i + j+q] = Episode[99*i -1+q] + Episode[99*i + j+q]

3131.0 + 43.0 = 3174.0
3131.0 + 114.0 = 3245.0
3131.0 + 181.0 = 3312.0
3131.0 + 249.0 = 3380.0
3131.0 + 333.0 = 3464.0
3131.0 + 409.0 = 3540.0
3131.0 + 462.0 = 3593.0
3131.0 + 545.0 = 3676.0
3131.0 + 622.0 = 3753.0
3131.0 + 687.0 = 3818.0
3131.0 + 738.0 = 3869.0
3131.0 + 795.0 = 3926.0
3131.0 + 840.0 = 3971.0
3131.0 + 887.0 = 4018.0
3131.0 + 930.0 = 4061.0
3131.0 + 970.0 = 4101.0
3131.0 + 1020.0 = 4151.0
3131.0 + 1062.0 = 4193.0
3131.0 + 1105.0 = 4236.0
3131.0 + 1145.0 = 4276.0
3131.0 + 1190.0 = 4321.0
3131.0 + 1236.0 = 4367.0
3131.0 + 1274.0 = 4405.0
3131.0 + 1329.0 = 4460.0
3131.0 + 1374.0 = 4505.0
3131.0 + 1415.0 = 4546.0
3131.0 + 1449.0 = 4580.0
3131.0 + 1479.0 = 4610.0
3131.0 + 1509.0 = 4640.0
3131.0 + 1559.0 = 4690.0
3131.0 + 1606.0 = 4737.0
3131.0 + 1639.0 = 4770.0
3131.0 + 1675.0 = 4806.0
3131.0 + 1716.0 = 4847.0
3131.0 + 1761.0 = 4892.0
3131.0 + 1789.0 = 4920.0
3131.0 + 1836.0 = 4967.0
3131.0 + 1858.0 = 4989.0
3131.0 + 1885.0 = 5016.0
3131.0 + 1910.0 = 5041.0
3131.0 + 1934.0 =

In [11]:
image.shape

(25612, 160, 120, 3)

In [12]:
Episode

array([   40.,    84.,   137.,   204.,   273.,   348.,   409.,   468.,
         513.,   569.,   631.,   687.,   738.,   787.,   842.,   893.,
         946.,   981.,  1020.,  1056.,  1098.,  1149.,  1197.,  1252.,
        1294.,  1332.,  1358.,  1392.,  1424.,  1459.,  1496.,  1529.,
        1568.,  1606.,  1633.,  1662.,  1688.,  1716.,  1747.,  1771.,
        1797.,  1828.,  1854.,  1883.,  1915.,  1957.,  1987.,  2016.,
        2041.,  2063.,  2087.,  2106.,  2124.,  2143.,  2160.,  2185.,
        2215.,  2242.,  2264.,  2290.,  2317.,  2346.,  2373.,  2400.,
        2422.,  2449.,  2466.,  2483.,  2507.,  2528.,  2553.,  2574.,
        2597.,  2617.,  2636.,  2659.,  2681.,  2703.,  2723.,  2741.,
        2757.,  2779.,  2798.,  2819.,  2842.,  2864.,  2885.,  2910.,
        2932.,  2953.,  2976.,  2994.,  3012.,  3033.,  3058.,  3076.,
        3093.,  3112.,  3131.,  3174.,  3245.,  3312.,  3380.,  3464.,
        3540.,  3593.,  3676.,  3753.,  3818.,  3869.,  3926.,  3971.,
      

In [13]:
Episode[0]

40.0

In [14]:
np.array_equal(image[22289], np.zeros([160,120,3]))

True

In [15]:
19256+6

19262

In [16]:
image_to_delete = [0,1,3132,6457,9838,12746,16090,19262,22289]
image_to_delete_episode = [98,197,296,395,494,594,693]

In [17]:
image = np.delete(image,image_to_delete,axis=0)

In [18]:
image.shape

(25603, 160, 120, 3)

In [19]:
Episode[693]

22282.0

In [20]:
import cv2

cv2.imwrite('kir_to_hossein.jpg', image[22281])

True

In [21]:
cv2.imwrite('3129.jpg', image[3129])
cv2.imwrite('3130.jpg', image[3130])
cv2.imwrite('6453.jpg', image[6453])
cv2.imwrite('6454.jpg', image[6454])
cv2.imwrite('9833.jpg', image[9833])
cv2.imwrite('9834.jpg', image[9834])
cv2.imwrite('12740.jpg', image[12740])
cv2.imwrite('12741.jpg', image[12741])
cv2.imwrite('16083.jpg', image[16083])
cv2.imwrite('16084.jpg', image[16084])
cv2.imwrite('19254.jpg', image[19254])
cv2.imwrite('19255.jpg', image[19255])
cv2.imwrite('22280.jpg', image[22280])
cv2.imwrite('22281.jpg', image[22281])

True

In [22]:
Episode = np.add(Episode,-1*np.ones(793))

In [23]:
Episode

array([   39.,    83.,   136.,   203.,   272.,   347.,   408.,   467.,
         512.,   568.,   630.,   686.,   737.,   786.,   841.,   892.,
         945.,   980.,  1019.,  1055.,  1097.,  1148.,  1196.,  1251.,
        1293.,  1331.,  1357.,  1391.,  1423.,  1458.,  1495.,  1528.,
        1567.,  1605.,  1632.,  1661.,  1687.,  1715.,  1746.,  1770.,
        1796.,  1827.,  1853.,  1882.,  1914.,  1956.,  1986.,  2015.,
        2040.,  2062.,  2086.,  2105.,  2123.,  2142.,  2159.,  2184.,
        2214.,  2241.,  2263.,  2289.,  2316.,  2345.,  2372.,  2399.,
        2421.,  2448.,  2465.,  2482.,  2506.,  2527.,  2552.,  2573.,
        2596.,  2616.,  2635.,  2658.,  2680.,  2702.,  2722.,  2740.,
        2756.,  2778.,  2797.,  2818.,  2841.,  2863.,  2884.,  2909.,
        2931.,  2952.,  2975.,  2993.,  3011.,  3032.,  3057.,  3075.,
        3092.,  3111.,  3130.,  3173.,  3244.,  3311.,  3379.,  3463.,
        3539.,  3592.,  3675.,  3752.,  3817.,  3868.,  3925.,  3970.,
      

# let's create R&theta

In [24]:
current_pose = np.load('current_pose_per_episode.npy')
current_pose

array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[ 3.47521356e-04,  1.02529747e-03,  3.15082150e-03]],

       ...,

       [[ 8.31446854e-01, -5.90037336e+00,  1.73261056e-01]],

       [[ 8.70971539e-01, -5.91455445e+00,  1.34571399e-01]],

       [[ 8.71368930e-01, -5.91465381e+00,  1.34097400e-01]]])

In [25]:
for i in range(25612):
    if np.array_equal(current_pose[i] , np.array([[0., 0., 0.]])):
        print(i)

0
1
3132
6457
9838
12746
16090
19262
22289


In [27]:
Velocity = np.delete(velocity,image_to_delete,axis=0)

In [28]:
for i in range(19):
    print(f'current ==> {current_pose[3128-i]} $$$$ vel ==> [{Velocity[3128-i][0][0]},{Velocity[3128-i][1][2]}]')

current ==> [[0.25545775 0.96298868 0.41144153]] $$$$ vel ==> [0.0,0.0]
current ==> [[0.23497531 0.94134253 0.40990952]] $$$$ vel ==> [0.0,-0.0]
current ==> [[0.18051663 0.88148373 0.39564853]] $$$$ vel ==> [0.14314760267734528,0.20981982350349426]
current ==> [[0.12875016 0.82435794 0.40718874]] $$$$ vel ==> [0.1431865245103836,-0.08863086253404616]
current ==> [[0.07713834 0.76584629 0.41346978]] $$$$ vel ==> [0.14473660290241241,-0.0002566942712292075]
current ==> [[0.01032273 0.68891521 0.41931607]] $$$$ vel ==> [0.17275042831897736,0.050436291843652725]
current ==> [[-0.07961398  0.57991321  0.4272664 ]] $$$$ vel ==> [0.17715513706207275,-0.04017693176865578]
current ==> [[-0.17056509  0.47459374  0.40629715]] $$$$ vel ==> [0.23224349319934845,-0.05215016379952431]
current ==> [[-0.27294647  0.36266681  0.39934964]] $$$$ vel ==> [0.25999999046325684,0.06374344974756241]
current ==> [[-0.37966809  0.25135914  0.38584315]] $$$$ vel ==> [0.25999999046325684,0.0688132643699646]
curren

In [29]:
j = 0
for i in range(25612):
    if velocity[i][1][2]<0:
        j+=1
j

10926

In [30]:
velocity[140]

array([[ 2.49973208e-01,  1.45566037e-05,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -2.10218847e-01]])

In [31]:
Episode[97]

3111.0

In [32]:
from math import atan
def r_t(pose1,pose2):
    
    theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]
    
    if np.isnan(theta):
        theta = 0
    
    R = ((pose2[1]-pose1[1])**2 + (pose2[0]-pose1[0])**2)**0.5
    
    return [R,theta]

In [34]:
Current_pose = np.delete(current_pose,image_to_delete,axis = 0)

In [53]:
def episode_lengths(parameters):
    lengths = []
    prev_end = 0
    for end in parameters:
        length = end - prev_end
        lengths.append(length)
        prev_end = end
    return lengths


episode_lengths = episode_lengths(Episode)
r_t_data = []
for last,length in zip(Episode,episode_lengths):
    for i in range(int(length)):
        #print(f'{last - length + i+1} ==> {last} $$ {Current_pose[int(last - length + i+1 - 1)][0]} - {Current_pose[int(last)-1][0]} ==> {r_t(Current_pose[int(last - length + i+1 - 1)][0],Current_pose[int(last)-1][0])}')
        r_t_data.append(r_t(Current_pose[int(last - length + i+1 - 1)][0],Current_pose[int(last)-1][0]))

/tmp/ipykernel_22818/163088402.py:4: RuntimeWarning: invalid value encountered in double_scalars
  theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]


In [54]:
r_t_data = np.array(r_t_data)

In [48]:
r_t_data[1]

array([0.5045402 , 0.43228792])

In [36]:
for i in range(25603):
    print(i+1,' ==> ',Current_pose[i])

1  ==>  [[0.00034752 0.0010253  0.00315082]]
2  ==>  [[0.00034875 0.00102893 0.00316211]]
3  ==>  [[0.00034938 0.00103076 0.0031678 ]]
4  ==>  [[0.00826135 0.00108543 0.00333652]]
5  ==>  [[0.0235365  0.00120549 0.00570303]]
6  ==>  [[0.04203411 0.00154947 0.01112859]]
7  ==>  [[0.06122595 0.0020248  0.01284445]]
8  ==>  [[0.08096311 0.00273925 0.02494029]]
9  ==>  [[0.10168528 0.00417586 0.04545841]]
10  ==>  [[0.11454756 0.00553081 0.05953626]]
11  ==>  [[0.13849144 0.00901677 0.08550005]]
12  ==>  [[0.15517219 0.01221117 0.10328505]]
13  ==>  [[0.17160212 0.01593886 0.11901251]]
14  ==>  [[0.18719713 0.01996287 0.13293527]]
15  ==>  [[0.20173352 0.02413724 0.1470976 ]]
16  ==>  [[0.21532935 0.02848149 0.16009721]]
17  ==>  [[0.2242817  0.03154717 0.16863942]]
18  ==>  [[0.2418058  0.03808028 0.1862634 ]]
19  ==>  [[0.25499064 0.0435084  0.20331006]]
20  ==>  [[0.26829717 0.04955719 0.21875446]]
21  ==>  [[0.28126175 0.05585853 0.22961722]]
22  ==>  [[0.29396769 0.06237809 0.24011081

4845  ==>  [[1.24226472 1.22485329 0.69655714]]
4846  ==>  [[1.24226759 1.22478153 0.69603259]]
4847  ==>  [[1.24228348 1.22422688 0.69187481]]
4848  ==>  [[1.24258159 1.21903901 0.68725811]]
4849  ==>  [[1.24271622 1.2166907  0.6881895 ]]
4850  ==>  [[1.24228428 1.22418997 0.6915913 ]]
4851  ==>  [[1.23385072 1.10162816 0.77222694]]
4852  ==>  [[1.21093276 1.01893325 0.8166932 ]]
4853  ==>  [[1.18132903 0.94731988 0.84121247]]
4854  ==>  [[1.14472732 0.87016599 0.85228507]]
4855  ==>  [[1.1040682  0.79351383 0.8570507 ]]
4856  ==>  [[1.06693637 0.72477852 0.85658031]]
4857  ==>  [[1.02891712 0.64728998 0.84003073]]
4858  ==>  [[0.99636528 0.56777614 0.82021102]]
4859  ==>  [[0.96988918 0.48619552 0.7979471 ]]
4860  ==>  [[0.95150458 0.41102804 0.77443391]]
4861  ==>  [[0.93746319 0.32587949 0.75173382]]
4862  ==>  [[0.93000686 0.25037045 0.73081456]]
4863  ==>  [[0.9272149  0.16729082 0.70486873]]
4864  ==>  [[0.9302262  0.09119763 0.67973212]]
4865  ==>  [[0.93995285 0.00616418 0.651

9658  ==>  [[-0.75660514  1.06442874 -0.96989828]]
9659  ==>  [[-0.88362735  1.14031952 -0.9570339 ]]
9660  ==>  [[-1.00261092  1.22901472 -0.94006453]]
9661  ==>  [[-1.12077395  1.34347517 -0.91346586]]
9662  ==>  [[-1.20983328  1.45504913 -0.88804485]]
9663  ==>  [[-1.29202664  1.59159731 -0.85201699]]
9664  ==>  [[-1.34008076  1.70224194 -0.81918734]]
9665  ==>  [[-1.36790372  1.78823407 -0.79955195]]
9666  ==>  [[-1.39086262  1.87258955 -0.78677707]]
9667  ==>  [[-1.40740775  1.95367674 -0.76239739]]
9668  ==>  [[-1.41402377  2.01676707 -0.67710572]]
9669  ==>  [[-1.41341458  2.02372787 -0.7114622 ]]
9670  ==>  [[-1.41189692  2.02025053 -0.88307762]]
9671  ==>  [[-1.40873436  2.01754756 -0.97244401]]
9672  ==>  [[-1.40706705  2.01687002 -0.98472419]]
9673  ==>  [[-1.40655485  2.01668511 -0.98473212]]
9674  ==>  [[-1.40142193  2.01485924 -0.98481126]]
9675  ==>  [[-1.40136617  2.01483964 -0.98481234]]
9676  ==>  [[-1.52622716  2.0620263  -0.98442014]]
9677  ==>  [[-1.66151847  2.110

14438  ==>  [[-2.36991806  7.83501936 -0.99455981]]
14439  ==>  [[-2.40273009  7.82801203 -0.9941195 ]]
14440  ==>  [[-2.43529915  7.8207302  -0.99378769]]
14441  ==>  [[-2.46807134  7.81309631 -0.99288164]]
14442  ==>  [[-2.51895179  7.80050416 -0.99214976]]
14443  ==>  [[-2.55135143  7.79181484 -0.9911519 ]]
14444  ==>  [[-2.59225111  7.78035503 -0.99005498]]
14445  ==>  [[-2.61756676  7.7724396  -0.98796181]]
14446  ==>  [[-2.63961599  7.76463645 -0.98443916]]
14447  ==>  [[-2.65657311  7.75775576 -0.98069381]]
14448  ==>  [[-2.66224367  7.75523958 -0.97882277]]
14449  ==>  [[-2.63633278  7.76603428 -0.98317219]]
14450  ==>  [[-2.62528494  7.76993933 -0.98829166]]
14451  ==>  [[-2.61976007  7.77197407 -0.97072583]]
14452  ==>  [[-2.61830838  7.77294694 -0.94041727]]
14453  ==>  [[-2.61804984  7.77316042 -0.91909466]]
14454  ==>  [[-2.61820071  7.77300068 -0.91908677]]
14455  ==>  [[-2.61837442  7.77281711 -0.91909095]]
14456  ==>  [[-2.62024924  7.77084801 -0.91930112]]
14457  ==>  

19421  ==>  [[-0.62213215  1.89750689  0.99567797]]
19422  ==>  [[-0.63868594  1.9002976   0.99742093]]
19423  ==>  [[-0.66037691  1.90286183  0.99889696]]
19424  ==>  [[-0.67046059  1.90367531  0.99943613]]
19425  ==>  [[-0.68252564  1.90433916  0.99975579]]
19426  ==>  [[-0.69390787  1.90473532  0.99992256]]
19427  ==>  [[-0.72119483  1.90477376  0.99994682]]
19428  ==>  [[-0.74097628  1.90404281  0.99963519]]
19429  ==>  [[-0.7505055   1.903453    0.99939339]]
19430  ==>  [[-0.76502478  1.9022699   0.9988784 ]]
19431  ==>  [[-0.78009948  1.90056595  0.99781483]]
19432  ==>  [[-0.7851263   1.89986518  0.99730876]]
19433  ==>  [[-0.79447351  1.89833909  0.99618691]]
19434  ==>  [[-0.80386551  1.89656832  0.99506927]]
19435  ==>  [[-0.83640137  1.88892091  0.99119261]]
19436  ==>  [[-0.8499559   1.8849295   0.98821629]]
19437  ==>  [[-0.85452442  1.88344693  0.9871389 ]]
19438  ==>  [[-0.86317396  1.88044031  0.98486324]]
19439  ==>  [[-0.89369412  1.86776162  0.97722316]]
19440  ==>  

24268  ==>  [[2.39753595 3.45302974 0.99997429]]
24269  ==>  [[2.39753194 3.45302974 0.99997402]]
24270  ==>  [[2.28443019 3.45214823 0.99990943]]
24271  ==>  [[2.18201929 3.45921312 0.99869871]]
24272  ==>  [[2.09173366 3.47012051 0.99765584]]
24273  ==>  [[1.99969178 3.48368117 0.99686132]]
24274  ==>  [[1.8970626  3.50216175 0.99539556]]
24275  ==>  [[1.80467033 3.52033264 0.99526402]]
24276  ==>  [[1.71122663 3.53855374 0.99562764]]
24277  ==>  [[1.6090162  3.55686492 0.996518  ]]
24278  ==>  [[1.51523553 3.57186378 0.99706836]]
24279  ==>  [[1.42205762 3.58624362 0.9970833 ]]
24280  ==>  [[1.32395711 3.60119148 0.99734291]]
24281  ==>  [[1.23751474 3.61313798 0.99792713]]
24282  ==>  [[1.15898576 3.62280653 0.99826784]]
24283  ==>  [[1.08103083 3.631779   0.99846694]]
24284  ==>  [[1.01072592 3.63959581 0.99838788]]
24285  ==>  [[0.94932899 3.64692936 0.99800506]]
24286  ==>  [[0.8968382  3.65393704 0.99751881]]
24287  ==>  [[0.84422795 3.66171009 0.99689313]]
24288  ==>  [[0.7870

In [37]:
def r_tc(pose1,pose2):
    
    theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]
    print(f'{(pose2[1]-pose1[1])}/{(pose2[0]-pose1[0])}')
    print(atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])))
    
    if np.isnan(theta):
        theta = 0
    
    R = ((pose2[1]-pose1[1])**2 + (pose2[0]-pose1[0])**2)**0.5
    
    return [R,theta]

r_tc(Current_pose[127-1][0],Current_pose[136-1][0])

0.12085402756203312/-0.026760907208323248
-1.3528808719930019


[0.12378142886789256, -2.1327626366683683]

In [38]:
Current_pose[127-1][0]

array([0.46929413, 1.70048543, 0.77988176])

In [39]:
Current_pose[136-1][0]

array([0.44253323, 1.82133946, 0.78185485])

In [56]:
print(Current_pose.shape)
print(image.shape)
print(Velocity.shape)
print(r_t_data.shape)
Episode

(25603, 1, 3)
(25603, 160, 120, 3)
(25603, 2, 3)
(25603, 2)


array([   39.,    83.,   136.,   203.,   272.,   347.,   408.,   467.,
         512.,   568.,   630.,   686.,   737.,   786.,   841.,   892.,
         945.,   980.,  1019.,  1055.,  1097.,  1148.,  1196.,  1251.,
        1293.,  1331.,  1357.,  1391.,  1423.,  1458.,  1495.,  1528.,
        1567.,  1605.,  1632.,  1661.,  1687.,  1715.,  1746.,  1770.,
        1796.,  1827.,  1853.,  1882.,  1914.,  1956.,  1986.,  2015.,
        2040.,  2062.,  2086.,  2105.,  2123.,  2142.,  2159.,  2184.,
        2214.,  2241.,  2263.,  2289.,  2316.,  2345.,  2372.,  2399.,
        2421.,  2448.,  2465.,  2482.,  2506.,  2527.,  2552.,  2573.,
        2596.,  2616.,  2635.,  2658.,  2680.,  2702.,  2722.,  2740.,
        2756.,  2778.,  2797.,  2818.,  2841.,  2863.,  2884.,  2909.,
        2931.,  2952.,  2975.,  2993.,  3011.,  3032.,  3057.,  3075.,
        3092.,  3111.,  3130.,  3173.,  3244.,  3311.,  3379.,  3463.,
        3539.,  3592.,  3675.,  3752.,  3817.,  3868.,  3925.,  3970.,
      

In [57]:
np.save('Image_data_per_episode',image)
np.save('R_T_data',r_t_data)
np.save('Current_pose',Current_pose)
np.save('Velocity',Velocity)
np.save("Episode",Episode)

# test data

In [28]:
import numpy as np
image = np.load("test_image_data.npy")
velocity = np.load("test_velocity.npy")
current = np.load("test_current_pose.npy")
episode = np.load("episode_length.npy")

In [29]:
image.shape

(3099, 160, 120, 3)

In [30]:
velocity.shape

(3099, 2, 3)

In [31]:
current.shape

(3099, 1, 3)

In [32]:
episode = np.append(episode,3099)

In [33]:
episode = np.delete(episode,0)
episode

array([   1,   42,   83,  171,  226,  293,  392,  436,  529,  583,  641,
        694,  751,  803,  857,  922,  963, 1006, 1042, 1099, 1146, 1184,
       1222, 1260, 1291, 1331, 1360, 1389, 1424, 1469, 1504, 1540, 1585,
       1616, 1647, 1674, 1704, 1734, 1760, 1793, 1818, 1850, 1882, 1911,
       1945, 1970, 2000, 2024, 2049, 2074, 2095, 2110, 2129, 2148, 2169,
       2186, 2208, 2234, 2255, 2273, 2298, 2318, 2339, 2356, 2375, 2402,
       2420, 2437, 2454, 2476, 2496, 2514, 2536, 2557, 2573, 2592, 2612,
       2634, 2653, 2670, 2689, 2712, 2729, 2749, 2766, 2788, 2810, 2830,
       2846, 2873, 2901, 2934, 2958, 2984, 3009, 3035, 3054, 3068, 3083,
       3099])

In [34]:
episode = np.delete(episode,0)

In [35]:
element_to_add = -1*np.ones(99)
episode = np.add(episode,element_to_add)

In [36]:
episode

array([  41.,   82.,  170.,  225.,  292.,  391.,  435.,  528.,  582.,
        640.,  693.,  750.,  802.,  856.,  921.,  962., 1005., 1041.,
       1098., 1145., 1183., 1221., 1259., 1290., 1330., 1359., 1388.,
       1423., 1468., 1503., 1539., 1584., 1615., 1646., 1673., 1703.,
       1733., 1759., 1792., 1817., 1849., 1881., 1910., 1944., 1969.,
       1999., 2023., 2048., 2073., 2094., 2109., 2128., 2147., 2168.,
       2185., 2207., 2233., 2254., 2272., 2297., 2317., 2338., 2355.,
       2374., 2401., 2419., 2436., 2453., 2475., 2495., 2513., 2535.,
       2556., 2572., 2591., 2611., 2633., 2652., 2669., 2688., 2711.,
       2728., 2748., 2765., 2787., 2809., 2829., 2845., 2872., 2900.,
       2933., 2957., 2983., 3008., 3034., 3053., 3067., 3082., 3098.])

In [37]:
np.array_equal(image[0], np.zeros([160,120,3]))

True

In [38]:
image = np.delete(image,0,axis=0)

In [39]:
for i in range(int(image.shape[0])):
    if np.array_equal(image[i], np.zeros([160,120,3])):
        print('fuck')

In [40]:
image.shape

(3098, 160, 120, 3)

In [41]:
velocity = np.delete(velocity,0,axis=0)

In [42]:
j = 0
for i in range(3098):
    if velocity[i][1][2]<0:
        j+=1
j

1262

test R Theta

In [43]:
from math import atan
def r_t(pose1,pose2):
    
    theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]
    
    if np.isnan(theta):
        theta = 0
    
    R = ((pose2[1]-pose1[1])**2 + (pose2[0]-pose1[0])**2)**0.5
    
    return [R,theta]

In [48]:
current = np.load("test_current_pose.npy")
current.shape

(3099, 1, 3)

In [49]:
current = np.delete(current,0,axis=0)

In [50]:
current.shape

(3098, 1, 3)

In [51]:
Episode = episode
Current_pose = current

In [52]:
def episode_lengths(parameters):
    lengths = []
    prev_end = 0
    for end in parameters:
        length = end - prev_end
        lengths.append(length)
        prev_end = end
    return lengths


episode_lengths = episode_lengths(Episode)
r_t_data = []
for last,length in zip(Episode,episode_lengths):
    for i in range(int(length)):
        #print(f'{last - length + i+1} ==> {last} $$ {Current_pose[int(last - length + i+1 - 1)][0]} - {Current_pose[int(last)-1][0]} ==> {r_t(Current_pose[int(last - length + i+1 - 1)][0],Current_pose[int(last)-1][0])}')
        r_t_data.append(r_t(Current_pose[int(last - length + i+1 - 1)][0],Current_pose[int(last)-1][0]))

/tmp/ipykernel_4934/163088402.py:4: RuntimeWarning: invalid value encountered in double_scalars
  theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]


In [53]:
r_t_data = np.array(r_t_data)


3098

In [76]:
r_t_data[3081]

[0.0, 0]

In [72]:
r_t_data[3082]

[1.4474299398336048, 0.10405730542382353]

In [73]:
r_t_data[3083]

[1.4474069439884205, 0.10405558917098048]

In [74]:
r_t_data[3084]

[1.3372657400844814, 0.09839968570278632]

In [80]:
r_t_data[3096]

[6.777714603645958e-05, -0.19897485154795158]

In [70]:
Episode

array([  41.,   82.,  170.,  225.,  292.,  391.,  435.,  528.,  582.,
        640.,  693.,  750.,  802.,  856.,  921.,  962., 1005., 1041.,
       1098., 1145., 1183., 1221., 1259., 1290., 1330., 1359., 1388.,
       1423., 1468., 1503., 1539., 1584., 1615., 1646., 1673., 1703.,
       1733., 1759., 1792., 1817., 1849., 1881., 1910., 1944., 1969.,
       1999., 2023., 2048., 2073., 2094., 2109., 2128., 2147., 2168.,
       2185., 2207., 2233., 2254., 2272., 2297., 2317., 2338., 2355.,
       2374., 2401., 2419., 2436., 2453., 2475., 2495., 2513., 2535.,
       2556., 2572., 2591., 2611., 2633., 2652., 2669., 2688., 2711.,
       2728., 2748., 2765., 2787., 2809., 2829., 2845., 2872., 2900.,
       2933., 2957., 2983., 3008., 3034., 3053., 3067., 3082., 3098.])

In [82]:
np.save('test_Episode',Episode)
np.save('test_R_T_data',r_t_data)
np.save('test_Current',current)
np.save('test_Image',image)
np.save('test_velocity',velocity)

# how i first solved this shit

In [7]:
np.array_equal(image[2737], np.zeros([160,120,3]))

True

In [8]:
episode[199] = 6029

In [9]:
episode[299] = 9360

In [10]:
episode[199]

6029

In [4]:
for i in range(26886):
    if np.array_equal(image[i], np.zeros([160,120,3])):
        print(i)

In [93]:
import cv2

im = image[12937]
cv2.imwrite('image.png',im)

True

In [12]:
element_to_add_1 = -1*np.ones([800,])
element_to_add_2 = np.append(np.zeros(99),-1*np.ones([701,]))
element_to_add_3 = np.append(np.zeros(199),-1*np.ones([601,]))
element_to_add_4 = np.append(np.zeros(299),-1*np.ones([501,]))
element_to_add_5 = np.append(np.zeros(399),-1*np.ones([401,]))
element_to_add_6 = np.append(np.zeros(499),-1*np.ones([301,]))
element_to_add_7 = np.append(np.zeros(599),-1*np.ones([201,]))
element_to_add_8 = np.append(np.zeros(699),-1*np.ones([101,]))
element_to_add = [element_to_add_1,element_to_add_1,element_to_add_2,element_to_add_3,element_to_add_4,
                 element_to_add_5,element_to_add_6,element_to_add_7,element_to_add_8]

image_to_delete = [0,0,3742,7595,11099,14601,17779,20639,23925]

In [13]:
episode[99]

2737

In [14]:
for image_to,element_to in zip(image_to_delete,element_to_add):
    image = np.delete(image,[image_to],axis=0)

    print('********before********')
    print(episode)
    episode = np.add(episode,element_to)
    print('********after********')
    print(episode)

********before********
[   37    92   145   204   275   329   386   437   503   555   606   647
   692   750   790   832   858   894   933   971  1006  1041  1075  1106
  1140  1174  1201  1229  1261  1287  1319  1344  1370  1390  1424  1448
  1467  1491  1515  1539  1562  1588  1614  1637  1659  1678  1702  1723
  1744  1761  1779  1800  1819  1838  1857  1874  1890  1908  1923  1944
  1968  1988  2009  2031  2054  2073  2090  2107  2132  2151  2175  2194
  2212  2232  2253  2271  2293  2313  2328  2343  2364  2380  2415  2446
  2463  2491  2506  2522  2536  2551  2568  2587  2604  2623  2638  2656
  2672  2691  2709  2737  2781  2842  2904  2957  3032  3103  3167  3244
  3303  3362  3421  3477  3524  3588  3651  3710  3761  3829  3867  3924
  3967  4004  4043  4069  4122  4160  4189  4224  4264  4291  4317  4355
  4376  4411  4434  4464  4494  4517  4543  4575  4607  4635  4670  4696
  4726  4754  4782  4807  4829  4852  4881  4905  4929  4954  4979  5009
  5038  5064  5089  5112  51

********before********
[   36.    91.   144.   203.   274.   328.   385.   436.   502.   554.
   605.   646.   691.   749.   789.   831.   857.   893.   932.   970.
  1005.  1040.  1074.  1105.  1139.  1173.  1200.  1228.  1260.  1286.
  1318.  1343.  1369.  1389.  1423.  1447.  1466.  1490.  1514.  1538.
  1561.  1587.  1613.  1636.  1658.  1677.  1701.  1722.  1743.  1760.
  1778.  1799.  1818.  1837.  1856.  1873.  1889.  1907.  1922.  1943.
  1967.  1987.  2008.  2030.  2053.  2072.  2089.  2106.  2131.  2150.
  2174.  2193.  2211.  2231.  2252.  2270.  2292.  2312.  2327.  2342.
  2363.  2379.  2414.  2445.  2462.  2490.  2505.  2521.  2535.  2550.
  2567.  2586.  2603.  2622.  2637.  2655.  2671.  2690.  2708.  2736.
  2780.  2841.  2903.  2956.  3031.  3102.  3166.  3243.  3302.  3361.
  3420.  3476.  3523.  3587.  3650.  3709.  3760.  3828.  3866.  3923.
  3966.  4003.  4042.  4068.  4121.  4159.  4188.  4223.  4263.  4290.
  4316.  4354.  4375.  4410.  4433.  4463.  4493.  451

********before********
[   36.    91.   144.   203.   274.   328.   385.   436.   502.   554.
   605.   646.   691.   749.   789.   831.   857.   893.   932.   970.
  1005.  1040.  1074.  1105.  1139.  1173.  1200.  1228.  1260.  1286.
  1318.  1343.  1369.  1389.  1423.  1447.  1466.  1490.  1514.  1538.
  1561.  1587.  1613.  1636.  1658.  1677.  1701.  1722.  1743.  1760.
  1778.  1799.  1818.  1837.  1856.  1873.  1889.  1907.  1922.  1943.
  1967.  1987.  2008.  2030.  2053.  2072.  2089.  2106.  2131.  2150.
  2174.  2193.  2211.  2231.  2252.  2270.  2292.  2312.  2327.  2342.
  2363.  2379.  2414.  2445.  2462.  2490.  2505.  2521.  2535.  2550.
  2567.  2586.  2603.  2622.  2637.  2655.  2671.  2690.  2708.  2735.
  2779.  2840.  2902.  2955.  3030.  3101.  3165.  3242.  3301.  3360.
  3419.  3475.  3522.  3586.  3649.  3708.  3759.  3827.  3865.  3922.
  3965.  4002.  4041.  4067.  4120.  4158.  4187.  4222.  4262.  4289.
  4315.  4353.  4374.  4409.  4432.  4462.  4492.  451

********before********
[   36.    91.   144.   203.   274.   328.   385.   436.   502.   554.
   605.   646.   691.   749.   789.   831.   857.   893.   932.   970.
  1005.  1040.  1074.  1105.  1139.  1173.  1200.  1228.  1260.  1286.
  1318.  1343.  1369.  1389.  1423.  1447.  1466.  1490.  1514.  1538.
  1561.  1587.  1613.  1636.  1658.  1677.  1701.  1722.  1743.  1760.
  1778.  1799.  1818.  1837.  1856.  1873.  1889.  1907.  1922.  1943.
  1967.  1987.  2008.  2030.  2053.  2072.  2089.  2106.  2131.  2150.
  2174.  2193.  2211.  2231.  2252.  2270.  2292.  2312.  2327.  2342.
  2363.  2379.  2414.  2445.  2462.  2490.  2505.  2521.  2535.  2550.
  2567.  2586.  2603.  2622.  2637.  2655.  2671.  2690.  2708.  2735.
  2779.  2840.  2902.  2955.  3030.  3101.  3165.  3242.  3301.  3360.
  3419.  3475.  3522.  3586.  3649.  3708.  3759.  3827.  3865.  3922.
  3965.  4002.  4041.  4067.  4120.  4158.  4187.  4222.  4262.  4289.
  4315.  4353.  4374.  4409.  4432.  4462.  4492.  451

ValueError: operands could not be broadcast together with shapes (800,) (900,) 

In [17]:
np.array_equal(image[0], np.zeros([160,120,3]))

True

In [5]:
image.shape

(27074, 160, 120, 3)

In [14]:
print(f'99 ==> {episode[99]}')
print(f'100 ==> {episode[100]}')
print(f'199 ==> {episode[199]}')
print(f'200 ==> {episode[200]}')
print(f'299 ==> {episode[299]}')
print(f'300 ==> {episode[300]}')
print(f'399 ==> {episode[399]}')
print(f'400 ==> {episode[400]}')
print(f'499 ==> {episode[499]}')
print(f'500 ==> {episode[500]}')
print(f'599 ==> {episode[599]}')
print(f'600 ==> {episode[600]}')
print(f'699 ==> {episode[699]}')
print(f'700 ==> {episode[700]}')
print(f'799 ==> {episode[799]}')

99 ==> 3741.0
100 ==> 3808.0
199 ==> 7592.0
200 ==> 7651.0
299 ==> 11098.0
300 ==> 11153.0
399 ==> 14602.0
400 ==> 14672.0
499 ==> 17778.0
500 ==> 17850.0
599 ==> 20638.0
600 ==> 20714.0
699 ==> 23924.0
700 ==> 24013.0
799 ==> 27074.0


# Delete first episode data in each map

In [3]:
episode

array([  115.,   234.,   405.,   535.,   656.,   821.,   878.,   951.,
        1033.,  1149.,  1200.,  1259.,  1300.,  1347.,  1407.,  1454.,
        1497.,  1551.,  1614.,  1685.,  1719.,  1750.,  1774.,  1806.,
        1836.,  1874.,  1918.,  1956.,  1992.,  2020.,  2061.,  2082.,
        2120.,  2154.,  2178.,  2204.,  2231.,  2262.,  2289.,  2313.,
        2342.,  2375.,  2401.,  2441.,  2468.,  2508.,  2525.,  2551.,
        2588.,  2616.,  2646.,  2689.,  2713.,  2749.,  2794.,  2839.,
        2862.,  2891.,  2913.,  2943.,  2964.,  3001.,  3024.,  3045.,
        3069.,  3091.,  3118.,  3136.,  3160.,  3179.,  3207.,  3228.,
        3247.,  3268.,  3284.,  3307.,  3324.,  3339.,  3354.,  3369.,
        3393.,  3414.,  3433.,  3453.,  3469.,  3484.,  3504.,  3526.,
        3545.,  3564.,  3580.,  3595.,  3616.,  3635.,  3654.,  3669.,
        3686.,  3710.,  3725.,  3741.,  3808.,  3875.,  4042.,  4122.,
        4198.,  4493.,  4580.,  4649.,  4734.,  4810.,  4902.,  4953.,
      

In [4]:
to_delete = [
    [i for i in range(0,int(episode[0]))],
    [i for i in range(int(episode[99]),int(episode[100]))],
    [i for i in range(int(episode[199]),int(episode[200]))],
    [i for i in range(int(episode[299]),int(episode[300]))],
    [i for i in range(int(episode[399]),int(episode[400]))],
    [i for i in range(int(episode[499]),int(episode[500]))],
    [i for i in range(int(episode[599]),int(episode[600]))],
    [i for i in range(int(episode[699]),int(episode[700]))],
]
to_delete_unpacked = []

for i in to_delete:
    for j in i:
        to_delete_unpacked.append(j)

len(to_delete_unpacked)

603

In [5]:
length_of_episode_deleted = [115.0,
                            episode[100]-episode[99],
                            episode[200]-episode[199],
                             episode[300]-episode[299],
                             episode[400]-episode[399],
                             episode[500]-episode[499],
                             episode[600]-episode[599],
                             episode[700]-episode[699],
                            ]
length_of_episode_deleted

[115.0, 67.0, 59.0, 55.0, 70.0, 72.0, 76.0, 89.0]

In [ ]:
image = np.delete(image,to_delete_unpacked,axis=0)
velocity = np.delete(velocity,to_delete_unpacked,axis=0)

#delete episode lengths

#np.delete(episode,[0],axis=0)
element_to_add_1 = -115*np.ones([799,])

#np.delete(episode,[99],axis=0)
element_to_add_2 = np.append(np.zeros(99),-67*np.ones([699,]))

#np.delete(episode,[198],axis=0)
element_to_add_3 = np.append(np.zeros(198),-59*np.ones([599,]))

#np.delete(episode,[297],axis=0)
element_to_add_4 = np.append(np.zeros(297),-55*np.ones([499,]))

#np.delete(episode,[396],axis=0)
element_to_add_5 = np.append(np.zeros(396),-70*np.ones([399,]))

#np.delete(episode,[495],axis=0)
element_to_add_6 = np.append(np.zeros(495),-72*np.ones([299,]))

#np.delete(episode,[594],axis=0)
element_to_add_7 = np.append(np.zeros(594),-76*np.ones([199,]))

#np.delete(episode,[693],axis=0)
element_to_add_8 = np.append(np.zeros(693),-89*np.ones([99,]))

element_to_add = [element_to_add_1,element_to_add_2,element_to_add_3,element_to_add_4,
                 element_to_add_5,element_to_add_6,element_to_add_7,element_to_add_8]

for element_to,episodeioo in zip(element_to_add,[0,99,198,297,396,495,594,693]):
    
    print('********before********')
    print(episode.shape)
    print(element_to.shape)
    episode = np.delete(episode,[episodeioo],axis=0)
    episode = np.add(episode,element_to)
    print('********after********')
    print(episode.shape)
    print(element_to.shape)
    

# Test data

In [1]:
cd G:\project

G:\project


In [2]:
import numpy as np
image = np.load("test_image_data.npy")

velocity = np.load("test_velocity_data.npy")

episode = np.load("test_episode_length.npy")

In [3]:
image.shape

(4027, 160, 120, 3)

In [4]:
episode[-1] = 4027

In [5]:
episode

array([   0,   61,  149,  220,  294,  356,  433,  487,  573,  634,  703,
        783,  854, 1005, 1065, 1123, 1165, 1214, 1262, 1318, 1362, 1415,
       1444, 1488, 1521, 1556, 1593, 1667, 1703, 1740, 1773, 1808, 1877,
       1909, 2004, 2035, 2077, 2117, 2156, 2197, 2238, 2277, 2307, 2350,
       2392, 2430, 2460, 2497, 2524, 2552, 2586, 2619, 2666, 2703, 2743,
       2773, 2805, 2839, 2874, 2913, 2959, 2989, 3021, 3048, 3083, 3122,
       3153, 3183, 3206, 3228, 3258, 3289, 3318, 3364, 3396, 3424, 3447,
       3478, 3507, 3529, 3557, 3581, 3608, 3637, 3665, 3701, 3722, 3747,
       3767, 3792, 3814, 3839, 3855, 3876, 3899, 3923, 3947, 3964, 3986,
       4003, 4027], dtype=int64)

In [6]:
episode = np.delete(episode,0)

In [7]:
for i in range(4027):
    if np.array_equal(image[i], np.zeros([160,120,3])):
        print(i)

0


In [8]:
image = np.delete(image,0,axis=0)

In [9]:
for i in range(4026):
    if np.array_equal(image[i], np.zeros([160,120,3])):
        print(i)

In [10]:
velocity = np.delete(velocity,0,axis=0)

In [11]:
episode

array([  61,  149,  220,  294,  356,  433,  487,  573,  634,  703,  783,
        854, 1005, 1065, 1123, 1165, 1214, 1262, 1318, 1362, 1415, 1444,
       1488, 1521, 1556, 1593, 1667, 1703, 1740, 1773, 1808, 1877, 1909,
       2004, 2035, 2077, 2117, 2156, 2197, 2238, 2277, 2307, 2350, 2392,
       2430, 2460, 2497, 2524, 2552, 2586, 2619, 2666, 2703, 2743, 2773,
       2805, 2839, 2874, 2913, 2959, 2989, 3021, 3048, 3083, 3122, 3153,
       3183, 3206, 3228, 3258, 3289, 3318, 3364, 3396, 3424, 3447, 3478,
       3507, 3529, 3557, 3581, 3608, 3637, 3665, 3701, 3722, 3747, 3767,
       3792, 3814, 3839, 3855, 3876, 3899, 3923, 3947, 3964, 3986, 4003,
       4027], dtype=int64)

In [12]:
for i in range(100):
    episode[i] = episode[i]-1

In [13]:
episode

array([  60,  148,  219,  293,  355,  432,  486,  572,  633,  702,  782,
        853, 1004, 1064, 1122, 1164, 1213, 1261, 1317, 1361, 1414, 1443,
       1487, 1520, 1555, 1592, 1666, 1702, 1739, 1772, 1807, 1876, 1908,
       2003, 2034, 2076, 2116, 2155, 2196, 2237, 2276, 2306, 2349, 2391,
       2429, 2459, 2496, 2523, 2551, 2585, 2618, 2665, 2702, 2742, 2772,
       2804, 2838, 2873, 2912, 2958, 2988, 3020, 3047, 3082, 3121, 3152,
       3182, 3205, 3227, 3257, 3288, 3317, 3363, 3395, 3423, 3446, 3477,
       3506, 3528, 3556, 3580, 3607, 3636, 3664, 3700, 3721, 3746, 3766,
       3791, 3813, 3838, 3854, 3875, 3898, 3922, 3946, 3963, 3985, 4002,
       4026], dtype=int64)

In [14]:
image.shape

(4026, 160, 120, 3)

In [15]:
np.save("test_image_data",image)

np.save("test_velocity_data",velocity)

np.save("test_episode_length",episode)

# Delete first of test 

In [16]:
to_delete = [
    [i for i in range(0,int(episode[0]))],

]
to_delete_unpacked = []

for i in to_delete:
    for j in i:
        to_delete_unpacked.append(j)

len(to_delete_unpacked)

60

In [17]:
to_delete_unpacked

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59]

In [18]:
length_of_episode_deleted = [60.0
                            ]

In [20]:
velocity.shape

(4026, 2, 3)

In [21]:
image = np.delete(image,to_delete_unpacked,axis=0)
velocity = np.delete(velocity,to_delete_unpacked,axis=0)

#delete episode lengths

#np.delete(episode,[0],axis=0)
element_to_add_1 = -60*np.ones([99,])


element_to_add = [element_to_add_1]

for element_to,episodeioo in zip(element_to_add,[0]):
    
    print('********before********')
    print(episode.shape)
    print(element_to.shape)
    episode = np.delete(episode,[episodeioo],axis=0)
    episode = np.add(episode,element_to)
    print('********after********')
    print(episode.shape)
    print(element_to.shape)
    

********before********
(100,)
(99,)
********after********
(99,)
(99,)


In [24]:
episode

array([  88.,  159.,  233.,  295.,  372.,  426.,  512.,  573.,  642.,
        722.,  793.,  944., 1004., 1062., 1104., 1153., 1201., 1257.,
       1301., 1354., 1383., 1427., 1460., 1495., 1532., 1606., 1642.,
       1679., 1712., 1747., 1816., 1848., 1943., 1974., 2016., 2056.,
       2095., 2136., 2177., 2216., 2246., 2289., 2331., 2369., 2399.,
       2436., 2463., 2491., 2525., 2558., 2605., 2642., 2682., 2712.,
       2744., 2778., 2813., 2852., 2898., 2928., 2960., 2987., 3022.,
       3061., 3092., 3122., 3145., 3167., 3197., 3228., 3257., 3303.,
       3335., 3363., 3386., 3417., 3446., 3468., 3496., 3520., 3547.,
       3576., 3604., 3640., 3661., 3686., 3706., 3731., 3753., 3778.,
       3794., 3815., 3838., 3862., 3886., 3903., 3925., 3942., 3966.])

In [25]:
np.save("test_image_data",image)

np.save("test_velocity_data",velocity)

np.save("test_episode_length",episode)

In [28]:
episode

array([  88.,  159.,  233.,  295.,  372.,  426.,  512.,  573.,  642.,
        722.,  793.,  944., 1004., 1062., 1104., 1153., 1201., 1257.,
       1301., 1354., 1383., 1427., 1460., 1495., 1532., 1606., 1642.,
       1679., 1712., 1747., 1816., 1848., 1943., 1974., 2016., 2056.,
       2095., 2136., 2177., 2216., 2246., 2289., 2331., 2369., 2399.,
       2436., 2463., 2491., 2525., 2558., 2605., 2642., 2682., 2712.,
       2744., 2778., 2813., 2852., 2898., 2928., 2960., 2987., 3022.,
       3061., 3092., 3122., 3145., 3167., 3197., 3228., 3257., 3303.,
       3335., 3363., 3386., 3417., 3446., 3468., 3496., 3520., 3547.,
       3576., 3604., 3640., 3661., 3686., 3706., 3731., 3753., 3778.,
       3794., 3815., 3838., 3862., 3886., 3903., 3925., 3942., 3966.])