In [1]:
cd project/

/home/ali/project


In [2]:
ls

'Building a Vision Transformers (VIT) with Tensorflow 2 from Scratch - Human Emotions Detection.mp4'*
 data
 dummy_goal.npy
 goal.csv
 goal.ods
 images/
 networks.ipynb
 notes*
 proj/
'replacing notebook.ipynb'
'stack data'*
 vit.ipynb*


In [3]:
import pandas as pd
file = pd.read_csv("goal.csv",header=None)
from math import atan

In [4]:
file

0         1
0   0.861193  0.660527
1   1.456178  0.879822
2   0.779701  2.139945
3   1.651075  2.931393
4   2.487799  3.095120
..       ...       ...
65 -4.030282 -1.058722
66  0.707133 -1.826597
67  1.138831 -3.185229
68  3.220224 -1.445912
69  3.946647  1.595473

[70 rows x 2 columns]

In [2]:
def r_t(pose2,pose1 = [[0.0013064784228448718,0.0032157046744297046]]):

    theta = atan((pose2[1]-pose1[0][1])/(pose2[0]-pose1[0][0]))

    R = ((pose2[1]-pose1[0][1])**2 + (pose2[0]-pose1[0][0])**2)**0.5

    return [R,theta]


r_t_data = []

In [6]:
for i in range(70):
    pose2 = file.loc[i]
    data = r_t(pose2)
    r_t_data.append(data)

In [7]:
len(r_t_data)

70

In [8]:
r_t_data

[[1.082341843632208, 0.6526638886721463],
 [1.6985552632539564, 0.5422787827238819],
 [2.2740949869781066, 1.2214459499101635],
 [3.3609462506703367, 1.0577148554157134],
 [3.9676844786036165, 0.8935029397012212],
 [4.6654935756901486, 0.7621734368354878],
 [5.26548059437802, 0.5891967001123991],
 [5.04690229021721, 0.45625923976769106],
 [4.709320731548181, 0.252943132350028],
 [3.929165428875709, 0.1598284015157388],
 [2.4776139960547203, 0.1619949457089586],
 [1.3141876834650215, -0.2773615902668191],
 [1.2352811017148189, -0.7102388933955454],
 [1.8754255078370572, -0.6353838194161802],
 [2.528124579917911, -0.3678803690397344],
 [1.5410244438090424, -0.9205280951515189],
 [2.2267488378381977, -0.6100654875222734],
 [3.0495271540624964, -0.44081550393947544],
 [3.5044221406473, -0.4866613409829755],
 [3.89488444703934, -0.5854995445524661],
 [4.20654364590759, -0.6837087392368055],
 [4.3316713858112, -0.7722293807162741],
 [4.1882897438318745, -0.8518567021732183],
 [4.592553704627

In [9]:
import numpy as np
data = np.array(r_t_data)
data.shape

(70, 2)

In [10]:
np.save('dummy_goal',data)

In [11]:
ls

'Building a Vision Transformers (VIT) with Tensorflow 2 from Scratch - Human Emotions Detection.mp4'*
 data
 dummy_goal.npy
 goal.csv
 goal.ods
 images/
 networks.ipynb
 notes*
 proj/
'replacing notebook.ipynb'
'stack data'*
 vit.ipynb*


In [4]:
import numpy as np
data = np.load('dummy_goal.npy')


In [8]:
from math import sin,cos
def r_theta_to_X_Y(r,theta):
    x = r*cos(theta)
    y = r*sin(theta)
    
    return x,y

for i in data:
    x,y = r_theta_to_X_Y(i[0],i[1])
    print(x,'  ',y)

0.8598868545130711    0.6573115425068873
1.454871779643635    0.8766060044993302
0.7783942808444012    2.13672889093298
1.6497684013438652    2.92817757689357
2.486492850962185    3.09190449785662
3.3747239990728146    3.22150092889759
4.377653882540694    2.9259925451798208
4.530639149471755    2.22363028048135
4.559470540490615    1.1785288044794304
3.8790866736931244    0.6253219534355433
2.445175804898505    0.3996078034588253
1.2639610490816051    -0.3598495988266317
0.9365977104728841    -0.8054217087903258
1.509424900160515    -1.1130396696530196
2.358972168019635    -0.9092107577970338
0.9329360731939421    -1.2265343940348497
1.825066729284375    -1.2757514728476698
2.758004577881265    -1.3011635607218996
3.097555917944445    -1.6389392530128595
3.246137434674545    -2.1523746446642398
3.261061323364305    -2.65715797238007
3.103022843269465    -3.0223544181322293
2.758353617843085    -3.1517068863108495
3.2073884836407554    -3.28697560759003
2.421748133427455    -3.12168856

# near goals

In [1]:
cd project/

/home/ali/project


In [18]:
import numpy as np
array = np.loadtxt('near_goal.csv', delimiter=',')

In [19]:
array

array([[ 1.51457134,  1.53589971],
       [ 1.7658297 ,  0.7041546 ],
       [ 2.16434866,  0.24277265],
       [ 1.92692207, -0.43678647],
       [ 1.41647138, -0.9230538 ],
       [ 1.0783468 , -1.09072373],
       [-0.61265625,  1.14938667],
       [-0.92699674,  0.69702773],
       [ 1.78773202,  0.76827011],
       [-1.1623379 , -0.33043794]])

In [20]:
def r_t(pose2,pose1 = [[0.0013064784228448718,0.0032157046744297046]]):

    theta = atan((pose2[1]-pose1[0][1])/(pose2[0]-pose1[0][0]))

    R = ((pose2[1]-pose1[0][1])**2 + (pose2[0]-pose1[0][0])**2)**0.5

    return [R,theta]

In [21]:
from math import atan
goal = []
for i in range(10):
    goal.append(r_t(array[i]))

In [22]:
goal = np.array(goal)


In [23]:
goal

array([[ 2.15385487,  0.79177348],
       [ 1.89864623,  0.37812465],
       [ 2.17626722,  0.11030051],
       [ 1.97524614, -0.2246428 ],
       [ 1.69135061, -0.57955397],
       [ 1.53516102, -0.7931821 ],
       [ 1.3002531 , -1.07902608],
       [ 1.1589314 , -0.64183379],
       [ 1.94335392,  0.40462856],
       [ 1.21053418,  0.27923996]])

In [24]:
goal = np.repeat(goal,10,axis=0)

In [26]:
goal

array([[ 2.15385487,  0.79177348],
       [ 2.15385487,  0.79177348],
       [ 2.15385487,  0.79177348],
       [ 2.15385487,  0.79177348],
       [ 2.15385487,  0.79177348],
       [ 2.15385487,  0.79177348],
       [ 2.15385487,  0.79177348],
       [ 2.15385487,  0.79177348],
       [ 2.15385487,  0.79177348],
       [ 2.15385487,  0.79177348],
       [ 1.89864623,  0.37812465],
       [ 1.89864623,  0.37812465],
       [ 1.89864623,  0.37812465],
       [ 1.89864623,  0.37812465],
       [ 1.89864623,  0.37812465],
       [ 1.89864623,  0.37812465],
       [ 1.89864623,  0.37812465],
       [ 1.89864623,  0.37812465],
       [ 1.89864623,  0.37812465],
       [ 1.89864623,  0.37812465],
       [ 2.17626722,  0.11030051],
       [ 2.17626722,  0.11030051],
       [ 2.17626722,  0.11030051],
       [ 2.17626722,  0.11030051],
       [ 2.17626722,  0.11030051],
       [ 2.17626722,  0.11030051],
       [ 2.17626722,  0.11030051],
       [ 2.17626722,  0.11030051],
       [ 2.17626722,

In [27]:
np.random.shuffle(goal)

In [29]:
goal.shape

(100, 2)

In [31]:
np.save('near_goal',goal)