In [1]:
ls

 basic_marker.py*                          model5.py
 chatGPT_recommended.py*                   my_robot_controller.py*
 contact.py*                               pose_orien_data.npy*
 continue_goal_third_try.npy               reset.py*
 current_goal_pose_subscriber.py*          rosmsg
 current_pose.npy                          R_theta_data.npy
'Data Cleaning.ipynb'                      r_theta.ipynb
'Data Cleaning second try.ipynb'*          temporary.py*
'Data Cleaning third.ipynb'                test_current_pose_per_episode.npy
 hossein_jooon2.py*                        test_episode_length.npy*
 hossein_jooon.py*                         test_image_data_per_episode.npy*
 hossein_jooon_read_image_insideloop.py*   test.py*
 image_data.npy*                           test_velocity_data_per_episode.npy*
 image_subscriber.py*                      trained.py*
 image_vel_subscriber.py*                  train_final.py*
 location_continue_third_try.npy           train_model.py
 mobilenet_chec

In [2]:
import numpy as np

image = np.load("image_data_per_episode.npy")

velocity = np.load("velocity_data_per_episode.npy")

In [3]:
episode = np.load("episode_length.npy")
episode

array([   0,    1,   38,   89,  131,  188,  252,  302,  351,  402,  469,
        534,  594,  644,  713,  771,  815,  861,  906,  943,  983, 1016,
       1053, 1094, 1131, 1167, 1195, 1236, 1279, 1318, 1350, 1384, 1418,
       1459, 1487, 1519, 1553, 1579, 1600, 1626, 1651, 1676, 1707, 1741,
       1771, 1801, 1829, 1859, 1880, 1901, 1931, 1958,    1,   88,  133,
        176,  229,  268,  315,  363,  424,  486,  553,  597,  641,  686,
        729,  764,  797,  836,  875,  919,  957,  990, 1022, 1049, 1086,
       1123, 1162, 1195, 1237, 1273, 1314, 1345, 1388, 1424, 1456, 1486,
       1515, 1541, 1570, 1597, 1624, 1651, 1682, 1710, 1751, 1778, 1815,
       1839, 1870, 1896, 1924,    1,   41,   82,  152,  212,  257,  307,
        349,  397,  444,  499,  546,  596,  645,  691,  741,  797,  844,
        886,  931,  970, 1018, 1062, 1106, 1147, 1197, 1242, 1285, 1321,
       1358, 1400, 1441, 1483, 1519, 1555, 1586, 1625, 1676, 1715, 1749,
       1785, 1809, 1841, 1871, 1902, 1927, 1966, 19

In [4]:
image.shape

(21210, 160, 120, 3)

# Episode Cleaning

In [5]:
episode = np.delete(episode,0)
episode

array([   1,   38,   89,  131,  188,  252,  302,  351,  402,  469,  534,
        594,  644,  713,  771,  815,  861,  906,  943,  983, 1016, 1053,
       1094, 1131, 1167, 1195, 1236, 1279, 1318, 1350, 1384, 1418, 1459,
       1487, 1519, 1553, 1579, 1600, 1626, 1651, 1676, 1707, 1741, 1771,
       1801, 1829, 1859, 1880, 1901, 1931, 1958,    1,   88,  133,  176,
        229,  268,  315,  363,  424,  486,  553,  597,  641,  686,  729,
        764,  797,  836,  875,  919,  957,  990, 1022, 1049, 1086, 1123,
       1162, 1195, 1237, 1273, 1314, 1345, 1388, 1424, 1456, 1486, 1515,
       1541, 1570, 1597, 1624, 1651, 1682, 1710, 1751, 1778, 1815, 1839,
       1870, 1896, 1924,    1,   41,   82,  152,  212,  257,  307,  349,
        397,  444,  499,  546,  596,  645,  691,  741,  797,  844,  886,
        931,  970, 1018, 1062, 1106, 1147, 1197, 1242, 1285, 1321, 1358,
       1400, 1441, 1483, 1519, 1555, 1586, 1625, 1676, 1715, 1749, 1785,
       1809, 1841, 1871, 1902, 1927, 1966, 1994, 20

In [6]:



element_to_delete = [0,51,102,153,204,255,306,357,408,459]

#Episode = np.add(episode,element_to_add)
Episode = np.delete(episode,element_to_delete)
Episode

array([  38,   89,  131,  188,  252,  302,  351,  402,  469,  534,  594,
        644,  713,  771,  815,  861,  906,  943,  983, 1016, 1053, 1094,
       1131, 1167, 1195, 1236, 1279, 1318, 1350, 1384, 1418, 1459, 1487,
       1519, 1553, 1579, 1600, 1626, 1651, 1676, 1707, 1741, 1771, 1801,
       1829, 1859, 1880, 1901, 1931, 1958,   88,  133,  176,  229,  268,
        315,  363,  424,  486,  553,  597,  641,  686,  729,  764,  797,
        836,  875,  919,  957,  990, 1022, 1049, 1086, 1123, 1162, 1195,
       1237, 1273, 1314, 1345, 1388, 1424, 1456, 1486, 1515, 1541, 1570,
       1597, 1624, 1651, 1682, 1710, 1751, 1778, 1815, 1839, 1870, 1896,
       1924,   41,   82,  152,  212,  257,  307,  349,  397,  444,  499,
        546,  596,  645,  691,  741,  797,  844,  886,  931,  970, 1018,
       1062, 1106, 1147, 1197, 1242, 1285, 1321, 1358, 1400, 1441, 1483,
       1519, 1555, 1586, 1625, 1676, 1715, 1749, 1785, 1809, 1841, 1871,
       1902, 1927, 1966, 1994, 2022, 2047, 2069,   

In [7]:
Episode.shape

(500,)

In [8]:
q=0
for i in range(1,10):

    for j in range(0,50):
        print(f'{Episode[50*i -1+q]} + {Episode[50*i + j+q]} = {Episode[50*i + j+q] + Episode[50*i -1+q]}')
        Episode[50*i + j+q] = Episode[50*i -1+q] + Episode[50*i + j+q]

1958 + 88 = 2046
1958 + 133 = 2091
1958 + 176 = 2134
1958 + 229 = 2187
1958 + 268 = 2226
1958 + 315 = 2273
1958 + 363 = 2321
1958 + 424 = 2382
1958 + 486 = 2444
1958 + 553 = 2511
1958 + 597 = 2555
1958 + 641 = 2599
1958 + 686 = 2644
1958 + 729 = 2687
1958 + 764 = 2722
1958 + 797 = 2755
1958 + 836 = 2794
1958 + 875 = 2833
1958 + 919 = 2877
1958 + 957 = 2915
1958 + 990 = 2948
1958 + 1022 = 2980
1958 + 1049 = 3007
1958 + 1086 = 3044
1958 + 1123 = 3081
1958 + 1162 = 3120
1958 + 1195 = 3153
1958 + 1237 = 3195
1958 + 1273 = 3231
1958 + 1314 = 3272
1958 + 1345 = 3303
1958 + 1388 = 3346
1958 + 1424 = 3382
1958 + 1456 = 3414
1958 + 1486 = 3444
1958 + 1515 = 3473
1958 + 1541 = 3499
1958 + 1570 = 3528
1958 + 1597 = 3555
1958 + 1624 = 3582
1958 + 1651 = 3609
1958 + 1682 = 3640
1958 + 1710 = 3668
1958 + 1751 = 3709
1958 + 1778 = 3736
1958 + 1815 = 3773
1958 + 1839 = 3797
1958 + 1870 = 3828
1958 + 1896 = 3854
1958 + 1924 = 3882
3882 + 41 = 3923
3882 + 82 = 3964
3882 + 152 = 4034
3882 + 212 = 4094
38

In [9]:
Episode

array([   38,    89,   131,   188,   252,   302,   351,   402,   469,
         534,   594,   644,   713,   771,   815,   861,   906,   943,
         983,  1016,  1053,  1094,  1131,  1167,  1195,  1236,  1279,
        1318,  1350,  1384,  1418,  1459,  1487,  1519,  1553,  1579,
        1600,  1626,  1651,  1676,  1707,  1741,  1771,  1801,  1829,
        1859,  1880,  1901,  1931,  1958,  2046,  2091,  2134,  2187,
        2226,  2273,  2321,  2382,  2444,  2511,  2555,  2599,  2644,
        2687,  2722,  2755,  2794,  2833,  2877,  2915,  2948,  2980,
        3007,  3044,  3081,  3120,  3153,  3195,  3231,  3272,  3303,
        3346,  3382,  3414,  3444,  3473,  3499,  3528,  3555,  3582,
        3609,  3640,  3668,  3709,  3736,  3773,  3797,  3828,  3854,
        3882,  3923,  3964,  4034,  4094,  4139,  4189,  4231,  4279,
        4326,  4381,  4428,  4478,  4527,  4573,  4623,  4679,  4726,
        4768,  4813,  4852,  4900,  4944,  4988,  5029,  5079,  5124,
        5167,  5203,

# clear Image and Velocity

In [10]:
Episode[49]

1958

In [12]:
np.array_equal(image[Episode[449]], np.zeros([160,120,3]))

True

In [13]:
element_to_delete = [0,1,Episode[49],Episode[99],Episode[149],Episode[199],Episode[249],
                   Episode[299],Episode[349],Episode[399],Episode[449]]

In [14]:
image = np.delete(image,element_to_delete,axis=0)
velocity = np.delete(velocity,element_to_delete,axis=0)

In [15]:
element_to_add_1 = -1*np.ones([500,])
element_to_add_2 = np.append(np.zeros(50),-1*np.ones([450,]))
element_to_add_3 = np.append(np.zeros(100),-1*np.ones([400,]))
element_to_add_4 = np.append(np.zeros(150),-1*np.ones([350,]))
element_to_add_5 = np.append(np.zeros(200),-1*np.ones([300,]))
element_to_add_6 = np.append(np.zeros(250),-1*np.ones([250,]))
element_to_add_7 = np.append(np.zeros(300),-1*np.ones([200,]))
element_to_add_8 = np.append(np.zeros(350),-1*np.ones([150,]))
element_to_add_9 = np.append(np.zeros(400),-1*np.ones([100,]))
element_to_add_10 = np.append(np.zeros(450),-1*np.ones([50,]))
element_to_add = [element_to_add_1,element_to_add_1,element_to_add_2,element_to_add_3,element_to_add_4,
                 element_to_add_5,element_to_add_6,element_to_add_7,element_to_add_8,
                 element_to_add_9,element_to_add_10]

In [16]:
for element_to in element_to_add:
    Episode = np.add(Episode,element_to)

In [17]:
Episode

array([   36.,    87.,   129.,   186.,   250.,   300.,   349.,   400.,
         467.,   532.,   592.,   642.,   711.,   769.,   813.,   859.,
         904.,   941.,   981.,  1014.,  1051.,  1092.,  1129.,  1165.,
        1193.,  1234.,  1277.,  1316.,  1348.,  1382.,  1416.,  1457.,
        1485.,  1517.,  1551.,  1577.,  1598.,  1624.,  1649.,  1674.,
        1705.,  1739.,  1769.,  1799.,  1827.,  1857.,  1878.,  1899.,
        1929.,  1956.,  2043.,  2088.,  2131.,  2184.,  2223.,  2270.,
        2318.,  2379.,  2441.,  2508.,  2552.,  2596.,  2641.,  2684.,
        2719.,  2752.,  2791.,  2830.,  2874.,  2912.,  2945.,  2977.,
        3004.,  3041.,  3078.,  3117.,  3150.,  3192.,  3228.,  3269.,
        3300.,  3343.,  3379.,  3411.,  3441.,  3470.,  3496.,  3525.,
        3552.,  3579.,  3606.,  3637.,  3665.,  3706.,  3733.,  3770.,
        3794.,  3825.,  3851.,  3879.,  3919.,  3960.,  4030.,  4090.,
        4135.,  4185.,  4227.,  4275.,  4322.,  4377.,  4424.,  4474.,
      

In [18]:
image.shape

(21199, 160, 120, 3)

# let's create R&theta

In [19]:
current_pose = np.load('current_pose_per_episode.npy')
current_pose

array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[ 3.56172866e-04,  1.05078390e-03,  3.23003244e-03]],

       ...,

       [[-9.82327483e-01,  1.82410636e+00, -9.75722559e-01]],

       [[-9.80550307e-01,  1.82343916e+00, -9.86786605e-01]],

       [[-9.80194544e-01,  1.82332391e+00, -9.86798468e-01]]])

In [20]:
for i in range(21210):
    if np.array_equal(current_pose[i] , np.array([[0., 0., 0.]])):
        print(i)

0
1
1958
3882
5951
8297
10610
12798
14936
16894
18959


In [21]:
for i in range(21199):
    if np.array_equal(image[i], np.zeros([160,120,3])):
        print(i)

In [24]:
element_to_delete

[0, 1, 1958, 3882, 5951, 8297, 10610, 12798, 14936, 16894, 18959]

In [23]:
from math import atan
def r_t(pose1,pose2):
    
    theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]
    
    if np.isnan(theta):
        theta = 0
    
    R = ((pose2[1]-pose1[1])**2 + (pose2[0]-pose1[0])**2)**0.5
    
    return [R,theta]

In [25]:
Current_pose = np.delete(current_pose,element_to_delete,axis = 0)

In [26]:
def episode_lengths(parameters):
    lengths = []
    prev_end = 0
    for end in parameters:
        length = end - prev_end
        lengths.append(length)
        prev_end = end
    return lengths


episode_lengths = episode_lengths(Episode)
r_t_data = []
for last,length in zip(Episode,episode_lengths):
    for i in range(int(length)):
        #print(f'{last - length + i+1} ==> {last} $$ {Current_pose[int(last - length + i+1 - 1)][0]} - {Current_pose[int(last)-1][0]} ==> {r_t(Current_pose[int(last - length + i+1 - 1)][0],Current_pose[int(last)-1][0])}')
        r_t_data.append(r_t(Current_pose[int(last - length + i+1 - 1)][0],Current_pose[int(last)-1][0]))

/tmp/ipykernel_20888/163088402.py:4: RuntimeWarning: invalid value encountered in double_scalars
  theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]


In [27]:
r_t_data = np.array(r_t_data)

In [28]:
r_t_data[1]

array([0.49851354, 0.37346193])

In [29]:
for i in range(25603):
    print(i+1,' ==> ',Current_pose[i])

1  ==>  [[0.00035617 0.00105078 0.00323003]]
2  ==>  [[0.0003571  0.00105352 0.00323853]]
3  ==>  [[0.00085534 0.00105977 0.00325785]]
4  ==>  [[0.00826956 0.00111124 0.00341672]]
5  ==>  [[0.02328134 0.00124109 0.0062909 ]]
6  ==>  [[0.04647359 0.00178325 0.01795372]]
7  ==>  [[0.06448899 0.00267563 0.03309195]]
8  ==>  [[0.07743432 0.00372069 0.04691784]]
9  ==>  [[0.10241182 0.0067134  0.06843953]]
10  ==>  [[0.11640189 0.00873888 0.0755089 ]]
11  ==>  [[0.14470106 0.01359179 0.09522169]]
12  ==>  [[0.15908217 0.01653734 0.10625456]]
13  ==>  [[0.17945048 0.02128014 0.12191555]]
14  ==>  [[0.19744746 0.02593477 0.13042118]]
15  ==>  [[0.21470217 0.03077332 0.14262141]]
16  ==>  [[0.22824823 0.03495371 0.1565336 ]]
17  ==>  [[0.24589991 0.04110791 0.17687598]]
18  ==>  [[0.26100745 0.04699312 0.19205068]]
19  ==>  [[0.27104978 0.05119387 0.20189201]]
20  ==>  [[0.28938721 0.05947214 0.21840728]]
21  ==>  [[0.29820025 0.06370723 0.22643669]]
22  ==>  [[0.31107415 0.07025005 0.24018036

4834  ==>  [[-1.80128492 -2.11278977 -0.9976724 ]]
4835  ==>  [[-2.06696964 -2.16429261 -0.98958429]]
4836  ==>  [[-2.09002509 -2.17143257 -0.98814231]]
4837  ==>  [[-2.11247714 -2.17864069 -0.98773424]]
4838  ==>  [[-2.14430195 -2.18941432 -0.98593432]]
4839  ==>  [[-2.16702123 -2.19741132 -0.98535513]]
4840  ==>  [[-2.19414697 -2.20716574 -0.98501428]]
4841  ==>  [[-2.21218707 -2.21369985 -0.98496406]]
4842  ==>  [[-2.23914351 -2.22357518 -0.98329151]]
4843  ==>  [[-2.2596098  -2.23223351 -0.97512402]]
4844  ==>  [[-2.27518184 -2.24097167 -0.95859677]]
4845  ==>  [[-2.27926897 -2.24373805 -0.95338838]]
4846  ==>  [[-2.27944466 -2.24386257 -0.95321932]]
4847  ==>  [[-2.27942603 -2.24385269 -0.95330655]]
4848  ==>  [[-2.27941091 -2.24384477 -0.95337909]]
4849  ==>  [[-2.27918187 -2.24381619 -0.95676177]]
4850  ==>  [[-2.27918425 -2.24381875 -0.9567863 ]]
4851  ==>  [[-2.27918792 -2.24382264 -0.95682287]]
4852  ==>  [[-2.27943577 -2.24399602 -0.95710939]]
4853  ==>  [[-2.28152858 -2.245

9618  ==>  [[ 2.9945931   3.97897455 -0.78890909]]
9619  ==>  [[ 2.99459819  3.97895358 -0.78892646]]
9620  ==>  [[ 2.99460345  3.97893195 -0.78894435]]
9621  ==>  [[ 2.99461367  3.97888991 -0.78897904]]
9622  ==>  [[ 2.99461896  3.97886822 -0.7889969 ]]
9623  ==>  [[ 2.99458013  3.97901239 -0.78859649]]
9624  ==>  [[ 2.99425007  3.98032392 -0.78535845]]
9625  ==>  [[ 2.99394494  3.98159919 -0.7826765 ]]
9626  ==>  [[ 2.99156604  3.99332926 -0.76663681]]
9627  ==>  [[ 2.98110768  4.06741444 -0.75752777]]
9628  ==>  [[ 2.97994624  4.07493329 -0.76067764]]
9629  ==>  [[ 2.97106178  4.1218421  -0.78043603]]
9630  ==>  [[ 2.96921604  4.12988474 -0.78468228]]
9631  ==>  [[ 2.95812853  4.17049412 -0.80414427]]
9632  ==>  [[ 2.93843173  4.22721848 -0.82395148]]
9633  ==>  [[ 2.9221746   4.26695715 -0.83687937]]
9634  ==>  [[ 2.90082414  4.31241    -0.8510293 ]]
9635  ==>  [[ 2.88492035  4.3428282  -0.85922525]]
9636  ==>  [[ 2.85987752  4.386615   -0.87022343]]
9637  ==>  [[ 2.83780223  4.421

14330  ==>  [[-4.26957694 -1.88037889 -0.51437342]]
14331  ==>  [[-4.23986503 -1.93304301 -0.49426731]]
14332  ==>  [[-4.20326343 -1.99058601 -0.46926661]]
14333  ==>  [[-4.15335833 -2.0612068  -0.44957021]]
14334  ==>  [[-4.1060774  -2.1229389  -0.43562447]]
14335  ==>  [[-4.06865338 -2.1690517  -0.42517336]]
14336  ==>  [[-4.02353321 -2.22158979 -0.40926833]]
14337  ==>  [[-3.98396404 -2.26541964 -0.40059904]]
14338  ==>  [[-3.92662046 -2.32681227 -0.3927129 ]]
14339  ==>  [[-3.87346673 -2.3810421  -0.38019105]]
14340  ==>  [[-3.83007787 -2.422888   -0.3700978 ]]
14341  ==>  [[-3.79127911 -2.45881288 -0.36282372]]
14342  ==>  [[-3.76154236 -2.48575491 -0.35729769]]
14343  ==>  [[-3.72936412 -2.51389166 -0.34745634]]
14344  ==>  [[-3.69622627 -2.54202507 -0.34239525]]
14345  ==>  [[-3.66673247 -2.56627649 -0.33077238]]
14346  ==>  [[-3.62485133 -2.59919085 -0.32228039]]
14347  ==>  [[-3.59402956 -2.62226862 -0.30725017]]
14348  ==>  [[-3.56895458 -2.6396506  -0.28556117]]
14349  ==>  

19088  ==>  [[ 1.87800283 -0.91618279 -0.03364487]]
19089  ==>  [[ 1.90239608 -0.91777693 -0.0304568 ]]
19090  ==>  [[ 1.92658871 -0.9191045  -0.02586841]]
19091  ==>  [[ 1.94330416 -0.91996072 -0.02439555]]
19092  ==>  [[ 1.98604347 -0.92167472 -0.01747097]]
19093  ==>  [[ 2.00166543 -0.92218442 -0.01478517]]
19094  ==>  [[ 2.03163625 -0.92286728 -0.00812785]]
19095  ==>  [[ 2.0453372  -0.92304909 -0.00531348]]
19096  ==>  [[ 2.06485872e+00 -9.23172367e-01 -6.63679542e-04]]
19097  ==>  [[ 2.08415481 -0.92310877  0.00458035]]
19098  ==>  [[ 2.10946086 -0.92265855  0.0134442 ]]
19099  ==>  [[ 2.1208798  -0.92232372  0.01511006]]
19100  ==>  [[ 2.13652641 -0.92180297  0.01819027]]
19101  ==>  [[ 2.15748907 -0.92093415  0.02388917]]
19102  ==>  [[ 2.16805471 -0.920392    0.02723944]]
19103  ==>  [[ 2.18811598 -0.91922116  0.03296912]]
19104  ==>  [[ 2.19775612 -0.91856147  0.03694235]]
19105  ==>  [[ 2.21205297 -0.91740455  0.04301122]]
19106  ==>  [[ 2.22625271 -0.91610628  0.04802326]]


IndexError: index 21199 is out of bounds for axis 0 with size 21199

In [30]:
def r_tc(pose1,pose2):
    
    theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]
    print(f'{(pose2[1]-pose1[1])}/{(pose2[0]-pose1[0])}')
    print(atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])))
    
    if np.isnan(theta):
        theta = 0
    
    R = ((pose2[1]-pose1[1])**2 + (pose2[0]-pose1[0])**2)**0.5
    
    return [R,theta]

r_tc(Current_pose[127-1][0],Current_pose[136-1][0])

0.007693116495199659/-0.03450866202355035
-0.2193460888912358


[0.03535578872072209, -1.2139385183478157]

In [31]:
Current_pose[127-1][0]

array([0.10014227, 1.17369821, 0.99459243])

In [32]:
Current_pose[136-1][0]

array([0.06563361, 1.18139133, 0.99583373])

In [34]:
print(Current_pose.shape)
print(image.shape)
print(velocity.shape)
print(r_t_data.shape)
Episode

(21199, 1, 3)
(21199, 160, 120, 3)
(21199, 2, 3)
(21199, 2)


array([   36.,    87.,   129.,   186.,   250.,   300.,   349.,   400.,
         467.,   532.,   592.,   642.,   711.,   769.,   813.,   859.,
         904.,   941.,   981.,  1014.,  1051.,  1092.,  1129.,  1165.,
        1193.,  1234.,  1277.,  1316.,  1348.,  1382.,  1416.,  1457.,
        1485.,  1517.,  1551.,  1577.,  1598.,  1624.,  1649.,  1674.,
        1705.,  1739.,  1769.,  1799.,  1827.,  1857.,  1878.,  1899.,
        1929.,  1956.,  2043.,  2088.,  2131.,  2184.,  2223.,  2270.,
        2318.,  2379.,  2441.,  2508.,  2552.,  2596.,  2641.,  2684.,
        2719.,  2752.,  2791.,  2830.,  2874.,  2912.,  2945.,  2977.,
        3004.,  3041.,  3078.,  3117.,  3150.,  3192.,  3228.,  3269.,
        3300.,  3343.,  3379.,  3411.,  3441.,  3470.,  3496.,  3525.,
        3552.,  3579.,  3606.,  3637.,  3665.,  3706.,  3733.,  3770.,
        3794.,  3825.,  3851.,  3879.,  3919.,  3960.,  4030.,  4090.,
        4135.,  4185.,  4227.,  4275.,  4322.,  4377.,  4424.,  4474.,
      

In [35]:
np.save('W_Image_data_per_episode',image)
np.save('W_R_T_data',r_t_data)
np.save('W_Current_pose',Current_pose)
np.save('W_Velocity',velocity)
np.save("W_Episode",Episode)

NameError: name 'Velocity' is not defined

In [36]:
np.save('W_Velocity',velocity)
np.save("W_Episode",Episode)

# Test

In [1]:
import numpy as np

image = np.load("image_data_per_episode.npy")

velocity = np.load("velocity_data_per_episode.npy")

In [2]:
episode = np.load("episode_length.npy")
episode

array([   0,    1,   45,  119,  186,  259,  324,  384,  435,  500,  577,
        668,  732,  782,  820,  878,  959, 1009, 1056, 1125, 1166, 1219,
       1262, 1298, 1351, 1384, 1418, 1472, 1509, 1553, 1589, 1622, 1656,
       1696, 1744, 1778, 1823, 1856, 1915, 1943, 1986, 2020, 2070, 2103,
       2134, 2159, 2187, 2221, 2261, 2294, 2323])

In [3]:
image.shape

(2357, 160, 120, 3)

In [4]:
episode = np.append(episode,2357)

In [5]:
episode = np.delete(episode,0)
episode

array([   1,   45,  119,  186,  259,  324,  384,  435,  500,  577,  668,
        732,  782,  820,  878,  959, 1009, 1056, 1125, 1166, 1219, 1262,
       1298, 1351, 1384, 1418, 1472, 1509, 1553, 1589, 1622, 1656, 1696,
       1744, 1778, 1823, 1856, 1915, 1943, 1986, 2020, 2070, 2103, 2134,
       2159, 2187, 2221, 2261, 2294, 2323, 2357])

In [6]:
Episode = np.delete(episode,0)
Episode

array([  45,  119,  186,  259,  324,  384,  435,  500,  577,  668,  732,
        782,  820,  878,  959, 1009, 1056, 1125, 1166, 1219, 1262, 1298,
       1351, 1384, 1418, 1472, 1509, 1553, 1589, 1622, 1656, 1696, 1744,
       1778, 1823, 1856, 1915, 1943, 1986, 2020, 2070, 2103, 2134, 2159,
       2187, 2221, 2261, 2294, 2323, 2357])

In [7]:
Episode.shape

(50,)

In [12]:
np.array_equal(image[2], np.zeros([160,120,3]))

False

In [13]:
element_to_delete = [0,1]

In [14]:
image = np.delete(image,element_to_delete,axis=0)
velocity = np.delete(velocity,element_to_delete,axis=0)

In [15]:
element_to_add_1 = -1*np.ones([50,])
element_to_add = [element_to_add_1,element_to_add_1]

In [16]:
for element_to in element_to_add:
    Episode = np.add(Episode,element_to)

In [17]:
Episode

array([  43.,  117.,  184.,  257.,  322.,  382.,  433.,  498.,  575.,
        666.,  730.,  780.,  818.,  876.,  957., 1007., 1054., 1123.,
       1164., 1217., 1260., 1296., 1349., 1382., 1416., 1470., 1507.,
       1551., 1587., 1620., 1654., 1694., 1742., 1776., 1821., 1854.,
       1913., 1941., 1984., 2018., 2068., 2101., 2132., 2157., 2185.,
       2219., 2259., 2292., 2321., 2355.])

In [18]:
image.shape

(2355, 160, 120, 3)

In [20]:
for i in range(2355):
    if np.array_equal(image[i], np.zeros([160,120,3])):
        print(i)

In [19]:
current_pose = np.load('current_pose_per_episode.npy')
current_pose

array([[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00]],

       [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00]],

       [[2.23435225e-04, 6.60752648e-04, 2.01799209e-03]],

       ...,

       [[2.28578765e+00, 3.41111386e+00, 9.49924844e-01]],

       [[2.28574280e+00, 3.41114587e+00, 9.49651691e-01]],

       [[2.28567128e+00, 3.41119640e+00, 9.49342972e-01]]])

In [21]:
for i in range(2355):
    if np.array_equal(current_pose[i] , np.array([[0., 0., 0.]])):
        print(i)

0
1


In [22]:
Current_pose = np.delete(current_pose,element_to_delete,axis = 0)

In [23]:
from math import atan
def r_t(pose1,pose2):
    
    theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]
    
    if np.isnan(theta):
        theta = 0
    
    R = ((pose2[1]-pose1[1])**2 + (pose2[0]-pose1[0])**2)**0.5
    
    return [R,theta]

In [24]:
def episode_lengths(parameters):
    lengths = []
    prev_end = 0
    for end in parameters:
        length = end - prev_end
        lengths.append(length)
        prev_end = end
    return lengths


episode_lengths = episode_lengths(Episode)
r_t_data = []
for last,length in zip(Episode,episode_lengths):
    for i in range(int(length)):
        #print(f'{last - length + i+1} ==> {last} $$ {Current_pose[int(last - length + i+1 - 1)][0]} - {Current_pose[int(last)-1][0]} ==> {r_t(Current_pose[int(last - length + i+1 - 1)][0],Current_pose[int(last)-1][0])}')
        r_t_data.append(r_t(Current_pose[int(last - length + i+1 - 1)][0],Current_pose[int(last)-1][0]))

/tmp/ipykernel_16109/163088402.py:4: RuntimeWarning: invalid value encountered in double_scalars
  theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]


In [25]:
r_t_data = np.array(r_t_data)

In [26]:
r_t_data[1]

array([0.64070658, 0.33422678])

In [27]:
def r_tc(pose1,pose2):
    
    theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]
    print(f'{(pose2[1]-pose1[1])}/{(pose2[0]-pose1[0])}')
    print(atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])))
    
    if np.isnan(theta):
        theta = 0
    
    R = ((pose2[1]-pose1[1])**2 + (pose2[0]-pose1[0])**2)**0.5
    
    return [R,theta]

r_tc(Current_pose[127-1][0],Current_pose[136-1][0])

0.13520039760527336/-0.1792189675069245
-0.6463026624082057


[0.22449629357045534, -1.6118227061926262]

In [28]:
print(Current_pose.shape)
print(image.shape)
print(velocity.shape)
print(r_t_data.shape)
Episode

(2355, 1, 3)
(2355, 160, 120, 3)
(2355, 2, 3)
(2355, 2)


array([  43.,  117.,  184.,  257.,  322.,  382.,  433.,  498.,  575.,
        666.,  730.,  780.,  818.,  876.,  957., 1007., 1054., 1123.,
       1164., 1217., 1260., 1296., 1349., 1382., 1416., 1470., 1507.,
       1551., 1587., 1620., 1654., 1694., 1742., 1776., 1821., 1854.,
       1913., 1941., 1984., 2018., 2068., 2101., 2132., 2157., 2185.,
       2219., 2259., 2292., 2321., 2355.])

In [29]:
np.save('W_test_Image_data_per_episode',image)
np.save('W_test_R_T_data',r_t_data)
np.save('W_teest_Current_pose',Current_pose)
np.save('W_test_Velocity',velocity)
np.save("W_test_Episode",Episode)