In [1]:
ls

 basic_marker.py*                          model4.py*
 chatGPT_recommended.py*                   model5.py
 contact.py*                               my_robot_controller.py*
 continue_goal_third_try.npy               pose_orien_data.npy*
 current_goal_pose_subscriber.py*          reset.py*
 current_pose.npy                          rosmsg
 current_pose_per_episode.npy              R_theta_data.npy
'Data Cleaning.ipynb'                      r_theta.ipynb
'Data Cleaning second try.ipynb'*          temporary.py*
'Data Cleaning third backup.ipynb'         test_current_pose_per_episode.npy
'Data Cleaning third.ipynb'                test_episode_length.npy*
 episode_length.npy*                       test_image_data_per_episode.npy*
 hossein_jooon2.py*                        test.py*
 hossein_jooon.py*                         test_velocity_data_per_episode.npy*
 hossein_jooon_read_image_insideloop.py*   trained.py*
 image_data.npy*                           train_final.py*
 image_data_per_epi

In [2]:
import numpy as np

image = np.load("image_data_per_episode.npy")

velocity = np.load("velocity_data_per_episode.npy")

In [3]:
episode = np.load("episode_length.npy")
episode = episode.astype(int)
episode

array([   0,    1,   44,   94,  145,  198,  248,  299,  360,  422,  485,
        535,  589,  658,  719,  770,  821,  880,  925,  995, 1047, 1107,
       1154, 1196, 1245, 1286, 1321, 1366, 1398, 1436, 1469, 1512, 1550,
       1588, 1633, 1682, 1721, 1752, 1814, 1843, 1886, 1912, 1936, 1957,
       1983, 2012, 2047, 2072, 2101, 2129, 2158, 2184,    1,   41,   92,
        142,  188,  251,  315,  371,  451,  506,  577,  625,  673,  735,
        781,  831,  898,  951,  995, 1040, 1089, 1140, 1183, 1249, 1277,
       1312, 1346, 1375, 1411, 1441, 1473, 1504, 1539, 1570, 1605, 1638,
       1666, 1704, 1736, 1764, 1795, 1839, 1880, 1916, 1945, 1980, 2011,
       2043, 2081, 2113, 2149,    1,   43,   96,  164,  225,  285,  336,
        407,  478,  529,  599,  662,  712,  759,  805,  846,  902,  945,
        984, 1033, 1067, 1118, 1174, 1241, 1286, 1338, 1382, 1427, 1472,
       1509, 1555, 1590, 1628, 1673, 1707, 1734, 1762, 1797, 1832, 1859,
       1887, 1918, 1964, 1993, 2025, 2059, 2086, 21

In [4]:
image.shape

(22229, 160, 120, 3)

# Episode Cleaning

In [5]:
episode = np.delete(episode,0)
episode

array([   1,   44,   94,  145,  198,  248,  299,  360,  422,  485,  535,
        589,  658,  719,  770,  821,  880,  925,  995, 1047, 1107, 1154,
       1196, 1245, 1286, 1321, 1366, 1398, 1436, 1469, 1512, 1550, 1588,
       1633, 1682, 1721, 1752, 1814, 1843, 1886, 1912, 1936, 1957, 1983,
       2012, 2047, 2072, 2101, 2129, 2158, 2184,    1,   41,   92,  142,
        188,  251,  315,  371,  451,  506,  577,  625,  673,  735,  781,
        831,  898,  951,  995, 1040, 1089, 1140, 1183, 1249, 1277, 1312,
       1346, 1375, 1411, 1441, 1473, 1504, 1539, 1570, 1605, 1638, 1666,
       1704, 1736, 1764, 1795, 1839, 1880, 1916, 1945, 1980, 2011, 2043,
       2081, 2113, 2149,    1,   43,   96,  164,  225,  285,  336,  407,
        478,  529,  599,  662,  712,  759,  805,  846,  902,  945,  984,
       1033, 1067, 1118, 1174, 1241, 1286, 1338, 1382, 1427, 1472, 1509,
       1555, 1590, 1628, 1673, 1707, 1734, 1762, 1797, 1832, 1859, 1887,
       1918, 1964, 1993, 2025, 2059, 2086, 2113, 21

In [6]:



element_to_delete = [0,51,102,153,204,255,306,357,408,459]

#Episode = np.add(episode,element_to_add)
Episode = np.delete(episode,element_to_delete)
Episode

array([  44,   94,  145,  198,  248,  299,  360,  422,  485,  535,  589,
        658,  719,  770,  821,  880,  925,  995, 1047, 1107, 1154, 1196,
       1245, 1286, 1321, 1366, 1398, 1436, 1469, 1512, 1550, 1588, 1633,
       1682, 1721, 1752, 1814, 1843, 1886, 1912, 1936, 1957, 1983, 2012,
       2047, 2072, 2101, 2129, 2158, 2184,   41,   92,  142,  188,  251,
        315,  371,  451,  506,  577,  625,  673,  735,  781,  831,  898,
        951,  995, 1040, 1089, 1140, 1183, 1249, 1277, 1312, 1346, 1375,
       1411, 1441, 1473, 1504, 1539, 1570, 1605, 1638, 1666, 1704, 1736,
       1764, 1795, 1839, 1880, 1916, 1945, 1980, 2011, 2043, 2081, 2113,
       2149,   43,   96,  164,  225,  285,  336,  407,  478,  529,  599,
        662,  712,  759,  805,  846,  902,  945,  984, 1033, 1067, 1118,
       1174, 1241, 1286, 1338, 1382, 1427, 1472, 1509, 1555, 1590, 1628,
       1673, 1707, 1734, 1762, 1797, 1832, 1859, 1887, 1918, 1964, 1993,
       2025, 2059, 2086, 2113, 2150, 2175, 2205,   

In [7]:
Episode.shape

(500,)

In [8]:
q=0
for i in range(1,10):

    for j in range(0,50):
        print(f'{Episode[50*i -1+q]} + {Episode[50*i + j+q]} = {Episode[50*i + j+q] + Episode[50*i -1+q]}')
        Episode[50*i + j+q] = Episode[50*i -1+q] + Episode[50*i + j+q]

2184 + 41 = 2225
2184 + 92 = 2276
2184 + 142 = 2326
2184 + 188 = 2372
2184 + 251 = 2435
2184 + 315 = 2499
2184 + 371 = 2555
2184 + 451 = 2635
2184 + 506 = 2690
2184 + 577 = 2761
2184 + 625 = 2809
2184 + 673 = 2857
2184 + 735 = 2919
2184 + 781 = 2965
2184 + 831 = 3015
2184 + 898 = 3082
2184 + 951 = 3135
2184 + 995 = 3179
2184 + 1040 = 3224
2184 + 1089 = 3273
2184 + 1140 = 3324
2184 + 1183 = 3367
2184 + 1249 = 3433
2184 + 1277 = 3461
2184 + 1312 = 3496
2184 + 1346 = 3530
2184 + 1375 = 3559
2184 + 1411 = 3595
2184 + 1441 = 3625
2184 + 1473 = 3657
2184 + 1504 = 3688
2184 + 1539 = 3723
2184 + 1570 = 3754
2184 + 1605 = 3789
2184 + 1638 = 3822
2184 + 1666 = 3850
2184 + 1704 = 3888
2184 + 1736 = 3920
2184 + 1764 = 3948
2184 + 1795 = 3979
2184 + 1839 = 4023
2184 + 1880 = 4064
2184 + 1916 = 4100
2184 + 1945 = 4129
2184 + 1980 = 4164
2184 + 2011 = 4195
2184 + 2043 = 4227
2184 + 2081 = 4265
2184 + 2113 = 4297
2184 + 2149 = 4333
4333 + 43 = 4376
4333 + 96 = 4429
4333 + 164 = 4497
4333 + 225 = 4558


In [9]:
Episode

array([   44,    94,   145,   198,   248,   299,   360,   422,   485,
         535,   589,   658,   719,   770,   821,   880,   925,   995,
        1047,  1107,  1154,  1196,  1245,  1286,  1321,  1366,  1398,
        1436,  1469,  1512,  1550,  1588,  1633,  1682,  1721,  1752,
        1814,  1843,  1886,  1912,  1936,  1957,  1983,  2012,  2047,
        2072,  2101,  2129,  2158,  2184,  2225,  2276,  2326,  2372,
        2435,  2499,  2555,  2635,  2690,  2761,  2809,  2857,  2919,
        2965,  3015,  3082,  3135,  3179,  3224,  3273,  3324,  3367,
        3433,  3461,  3496,  3530,  3559,  3595,  3625,  3657,  3688,
        3723,  3754,  3789,  3822,  3850,  3888,  3920,  3948,  3979,
        4023,  4064,  4100,  4129,  4164,  4195,  4227,  4265,  4297,
        4333,  4376,  4429,  4497,  4558,  4618,  4669,  4740,  4811,
        4862,  4932,  4995,  5045,  5092,  5138,  5179,  5235,  5278,
        5317,  5366,  5400,  5451,  5507,  5574,  5619,  5671,  5715,
        5760,  5805,

# clear Image and Velocity

In [10]:
Episode[49]

2184

In [11]:
np.array_equal(image[Episode[449]], np.zeros([160,120,3]))

True

In [12]:
element_to_delete = [0,1,Episode[49],Episode[99],Episode[149],Episode[199],Episode[249],
                   Episode[299],Episode[349],Episode[399],Episode[449]]

In [13]:
image = np.delete(image,element_to_delete,axis=0)
velocity = np.delete(velocity,element_to_delete,axis=0)

In [14]:
element_to_add_1 = -1*np.ones([500,])
element_to_add_2 = np.append(np.zeros(50),-1*np.ones([450,]))
element_to_add_3 = np.append(np.zeros(100),-1*np.ones([400,]))
element_to_add_4 = np.append(np.zeros(150),-1*np.ones([350,]))
element_to_add_5 = np.append(np.zeros(200),-1*np.ones([300,]))
element_to_add_6 = np.append(np.zeros(250),-1*np.ones([250,]))
element_to_add_7 = np.append(np.zeros(300),-1*np.ones([200,]))
element_to_add_8 = np.append(np.zeros(350),-1*np.ones([150,]))
element_to_add_9 = np.append(np.zeros(400),-1*np.ones([100,]))
element_to_add_10 = np.append(np.zeros(450),-1*np.ones([50,]))
element_to_add = [element_to_add_1,element_to_add_1,element_to_add_2,element_to_add_3,element_to_add_4,
                 element_to_add_5,element_to_add_6,element_to_add_7,element_to_add_8,
                 element_to_add_9,element_to_add_10]

In [15]:
for element_to in element_to_add:
    Episode = np.add(Episode,element_to)

In [16]:
Episode

array([   42.,    92.,   143.,   196.,   246.,   297.,   358.,   420.,
         483.,   533.,   587.,   656.,   717.,   768.,   819.,   878.,
         923.,   993.,  1045.,  1105.,  1152.,  1194.,  1243.,  1284.,
        1319.,  1364.,  1396.,  1434.,  1467.,  1510.,  1548.,  1586.,
        1631.,  1680.,  1719.,  1750.,  1812.,  1841.,  1884.,  1910.,
        1934.,  1955.,  1981.,  2010.,  2045.,  2070.,  2099.,  2127.,
        2156.,  2182.,  2222.,  2273.,  2323.,  2369.,  2432.,  2496.,
        2552.,  2632.,  2687.,  2758.,  2806.,  2854.,  2916.,  2962.,
        3012.,  3079.,  3132.,  3176.,  3221.,  3270.,  3321.,  3364.,
        3430.,  3458.,  3493.,  3527.,  3556.,  3592.,  3622.,  3654.,
        3685.,  3720.,  3751.,  3786.,  3819.,  3847.,  3885.,  3917.,
        3945.,  3976.,  4020.,  4061.,  4097.,  4126.,  4161.,  4192.,
        4224.,  4262.,  4294.,  4330.,  4372.,  4425.,  4493.,  4554.,
        4614.,  4665.,  4736.,  4807.,  4858.,  4928.,  4991.,  5041.,
      

In [17]:
image.shape

(22218, 160, 120, 3)

# let's create R&theta

In [18]:
import numpy as np

In [19]:
current_pose = np.load('current_pose_per_episode.npy')


In [20]:
current_pose.shape

(22229, 1, 7)

In [21]:
for i in range(21210):
    if np.array_equal(current_pose[i] , np.array([[0., 0., 0.,0.,0.,0.,0.]])):
        print(i)

0
1
2184
4333
6538
8765
11055
13314
15451
17781
19963


In [22]:
current_pose[1242].shape

(1, 7)

In [23]:
np.array([[0., 0., 0.,0.,0.,0.,0.]]).shape

(1, 7)

In [24]:
for i in range(21199):
    if np.array_equal(image[i], np.zeros([160,120,3])):
        print(i)

In [25]:
element_to_delete

[0, 1, 2184, 4333, 6538, 8765, 11055, 13314, 15451, 17781, 19963]

In [26]:
from math import atan
def r_t(pose1,pose2):
    
    theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]
    
    if np.isnan(theta):
        theta = 0
    
    R = ((pose2[1]-pose1[1])**2 + (pose2[0]-pose1[0])**2)**0.5
    
    return [R,theta]

In [27]:
Current_pose = np.delete(current_pose,element_to_delete,axis = 0)

### quaternion to eulerian

In [28]:
Current_pose.shape

(22218, 1, 7)

In [29]:
import numpy as np
import math
from scipy.spatial.transform import Rotation as R

def quaternion_to_euler(quaternion):
    r = R.from_quat(quaternion)
    euler = r.as_euler('xyz', degrees=True)
    return euler

# Extracting the quaternion orientations (last 4 elements in each row)
quaternions = Current_pose[:, 0, 3:]

# Converting quaternions to Euler angles
euler_angles = []
for quaternion in quaternions:
    euler_angles.append(quaternion_to_euler(quaternion))

# Converting the list to a NumPy array
euler_angles = np.array(euler_angles)
positions = Current_pose[:, 0, :3]

# Now you have the Euler angles for each timestamp in the "euler_angles_array" variable.
# The shape of euler_angles_array should be (22229, 3) where the three columns represent roll, pitch, and yaw angles in degrees respectively.


In [30]:
euler_angles.shape

(22218, 3)

In [31]:
Current_pose_euler = np.reshape(np.array([positions[:,0],positions[:,1],euler_angles[:,2]]),[22218, 3])
Current_pose_euler = Current_pose_euler.reshape(22218, 1, 3)

In [32]:
Current_pose_euler.shape

(22218, 1, 3)

In [33]:
def episode_lengths(parameters):
    lengths = []
    prev_end = 0
    for end in parameters:
        length = end - prev_end
        lengths.append(length)
        prev_end = end
    return lengths


episode_lengths = episode_lengths(Episode)
r_t_data = []
for last,length in zip(Episode,episode_lengths):
    for i in range(int(length)):
        #print(f'{last - length + i+1} ==> {last} $$ {Current_pose[int(last - length + i+1 - 1)][0]} - {Current_pose[int(last)-1][0]} ==> {r_t(Current_pose[int(last - length + i+1 - 1)][0],Current_pose[int(last)-1][0])}')
        r_t_data.append(r_t(Current_pose_euler[int(last - length + i+1 - 1)][0],Current_pose_euler[int(last)-1][0]))

/tmp/ipykernel_13963/163088402.py:4: RuntimeWarning: invalid value encountered in double_scalars
  theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]


In [34]:
r_t_data = np.array(r_t_data)

In [35]:
r_t_data[1]

array([2.10391559, 0.73786252])

In [36]:
for i in range(25603):
    print(i+1,' ==> ',Current_pose_euler[i])

1  ==>  [[0.00023571 0.00023632 0.00226011]]
2  ==>  [[0.00815067 0.0307601  0.04471951]]
3  ==>  [[0.07153233 0.08804106 0.10383883]]
4  ==>  [[0.11887142 0.13062819 0.15454072]]
5  ==>  [[0.16607294 0.18335696 0.20501909]]
6  ==>  [[0.22138676 0.23723915 0.24813089]]
7  ==>  [[0.26941345 0.27925489 0.29372877]]
8  ==>  [[0.30777914 0.32635376 0.33548004]]
9  ==>  [[0.35399161 0.36780657 0.38170512]]
10  ==>  [[0.3959278  0.40971608 0.42322328]]
11  ==>  [[0.4371845  0.45073881 0.46431862]]
12  ==>  [[0.47810597 0.48687238 0.5019143 ]]
13  ==>  [[0.5080933  0.51593661 0.52207615]]
14  ==>  [[0.52788842 0.53095654 0.53252294]]
15  ==>  [[0.53461453 0.53549109 0.5354999 ]]
16  ==>  [[0.5356075  0.53655565 0.54125421]]
17  ==>  [[0.552852   0.57037172 0.58999031]]
18  ==>  [[0.6122863  0.63493687 0.65719636]]
19  ==>  [[0.6783047  0.69228545 0.71977586]]
20  ==>  [[0.73289562 0.75103446 0.77312226]]
21  ==>  [[0.78871942 0.80336154 0.81275695]]
22  ==>  [[0.82927644 0.83654782 0.84999941

5249  ==>  [[-0.61013299 -0.63549352 -0.65494993]]
5250  ==>  [[-0.67582009 -0.70268229 -0.73792639]]
5251  ==>  [[-0.75213126 -0.79275786 -0.81827082]]
5252  ==>  [[-0.83634751 -0.84770491 -0.87438163]]
5253  ==>  [[-0.89554777 -0.91081452 -0.93429465]]
5254  ==>  [[-0.95247456 -0.96160654 -0.98900794]]
5255  ==>  [[-1.00264869 -1.01638649 -1.03472516]]
5256  ==>  [[-1.05769126 -1.07614519 -1.08999128]]
5257  ==>  [[-1.10394238 -1.12250905 -1.14472333]]
5258  ==>  [[-1.15168636 -1.15169084 -1.15170454]]
5259  ==>  [[-1.15292117 -1.15436514 -1.15892709]]
5260  ==>  [[-1.16541981 -1.16936879 -1.17372483]]
5261  ==>  [[-1.18293519 -1.18745165 -1.20472897]]
5262  ==>  [[-1.2425485  -1.25038636 -1.26709847]]
5263  ==>  [[-1.30001539 -1.30818697 -1.3399381 ]]
5264  ==>  [[-1.34780269 -1.37773401 -1.39920565]]
5265  ==>  [[-1.41305514 -1.45492507 -1.46175935]]
5266  ==>  [[-1.486994   -1.5093664  -1.53394308]]
5267  ==>  [[-1.55514248 -1.5665763  -1.58071327]]
5268  ==>  [[-1.59300973 -1.614

9956  ==>  [[-1.08731629 -1.08736436 -1.08912201]]
9957  ==>  [[-1.08913341 -1.08914516 -1.089168  ]]
9958  ==>  [[-1.08917979 -1.08954388 -1.09058543]]
9959  ==>  [[-1.09469073 -1.10109674 -1.10483901]]
9960  ==>  [[-1.12183396 -1.15530399 -1.17082838]]
9961  ==>  [[-1.2007694  -1.21683657 -1.27362515]]
9962  ==>  [[-1.32240792 -1.36470184 -1.40715012]]
9963  ==>  [[-1.4415968  -1.49284191 -1.52715861]]
9964  ==>  [[-1.57007484 -1.61188073 -1.65360341]]
9965  ==>  [[-1.70339314 -1.75330777 -1.79526066]]
9966  ==>  [[-1.83804866 -1.89666601 -1.9723283 ]]
9967  ==>  [[-2.00860824 -2.04824734 -2.07776383]]
9968  ==>  [[-2.11453907 -2.1388394  -2.15777042]]
9969  ==>  [[-2.18613783 -2.21454165 -2.23370627]]
9970  ==>  [[-2.25738035 -2.28571373 -2.30974534]]
9971  ==>  [[-2.33347062 -2.36505473 -2.37614949]]
9972  ==>  [[-2.38089115 -2.38191594 -2.38348092]]
9973  ==>  [[-2.38459621 -2.38600751 -2.38683103]]
9974  ==>  [[-2.38589758 -2.38589152 -2.38587312]]
9975  ==>  [[-2.38586685 -2.402

14998  ==>  [[155.59139682 154.62500583 153.06703776]]
14999  ==>  [[151.17969261 149.52999402 147.9517667 ]]
15000  ==>  [[146.50717914 145.021966   144.10162881]]
15001  ==>  [[142.63055342 141.98436765 140.71266533]]
15002  ==>  [[140.07195115 138.94772734 138.45925555]]
15003  ==>  [[137.23822143 136.23164497 134.33195094]]
15004  ==>  [[133.54856414 132.13707354 131.24973158]]
15005  ==>  [[129.51211818 128.22076973 126.86050966]]
15006  ==>  [[125.26148022 123.56654875 122.49108515]]
15007  ==>  [[121.54400961 120.4790214  120.50669694]]
15008  ==>  [[122.86344558 126.52803801 127.06377195]]
15009  ==>  [[127.69597439 127.7065521  127.79805025]]
15010  ==>  [[129.04883796 129.63478176 129.37981162]]
15011  ==>  [[126.87676524 124.90971671 121.38885352]]
15012  ==>  [[119.12737075 115.6757102  112.8008367 ]]
15013  ==>  [[109.72386553 106.75653671 104.87917916]]
15014  ==>  [[101.7604327   98.57271963  97.14847013]]
15015  ==>  [[95.34409009 93.75132789 91.17081984]]
15016  ==>  [

19980  ==>  [[-39.0361758  -38.8895503  -39.62657122]]
19981  ==>  [[-40.39370631 -41.47406822 -42.44457918]]
19982  ==>  [[-44.7830451  -47.58348766 -49.53946351]]
19983  ==>  [[-53.08735279 -54.89623206 -58.54324937]]
19984  ==>  [[-60.34053111 -63.62691511 -64.93537958]]
19985  ==>  [[-66.58127479 -68.35763178 -69.27037301]]
19986  ==>  [[-70.52228843 -72.62395218 -74.5027878 ]]
19987  ==>  [[-76.21009717 -78.11418216 -79.87250507]]
19988  ==>  [[-81.71349057 -83.53543587 -84.97195432]]
19989  ==>  [[-85.59618527 -87.47416578 -88.59261293]]
19990  ==>  [[-90.87815946 -91.96105891 -94.66717975]]
19991  ==>  [[-96.06526212 -97.75099882 -99.57977658]]
19992  ==>  [[-101.49518573 -102.24586934 -103.09721265]]
19993  ==>  [[-104.04251409 -104.90588297 -105.70541191]]
19994  ==>  [[-106.42192998 -107.09914037 -107.47643015]]
19995  ==>  [[-107.9479535  -108.38334431 -109.61057185]]
19996  ==>  [[-110.90787886 -111.11109261 -112.14560574]]
19997  ==>  [[-116.83097383 -120.2915155  -127.148

IndexError: index 22218 is out of bounds for axis 0 with size 22218

In [37]:
def r_tc(pose1,pose2):
    
    theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]
    print(f'{(pose2[1]-pose1[1])}/{(pose2[0]-pose1[0])}')
    print(atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])))
    
    if np.isnan(theta):
        theta = 0
    
    R = ((pose2[1]-pose1[1])**2 + (pose2[0]-pose1[0])**2)**0.5
    
    return [R,theta]

r_tc(Current_pose_euler[127-1][0],Current_pose_euler[136-1][0])

-0.37397327103303457/-0.3906412621366835
0.7636024076367411


[0.5407925694116817, -1.78188096858037]

In [38]:
Current_pose_euler[127-1][0]

array([2.59516241, 2.5699495 , 2.54548338])

In [39]:
Current_pose_euler[136-1][0]

array([2.20452115, 2.19597623, 2.18782323])

In [40]:
print(Current_pose_euler.shape)
print(image.shape)
print(velocity.shape)
print(r_t_data.shape)
Episode

(22218, 1, 3)
(22218, 160, 120, 3)
(22218, 2, 3)
(22218, 2)


array([   42.,    92.,   143.,   196.,   246.,   297.,   358.,   420.,
         483.,   533.,   587.,   656.,   717.,   768.,   819.,   878.,
         923.,   993.,  1045.,  1105.,  1152.,  1194.,  1243.,  1284.,
        1319.,  1364.,  1396.,  1434.,  1467.,  1510.,  1548.,  1586.,
        1631.,  1680.,  1719.,  1750.,  1812.,  1841.,  1884.,  1910.,
        1934.,  1955.,  1981.,  2010.,  2045.,  2070.,  2099.,  2127.,
        2156.,  2182.,  2222.,  2273.,  2323.,  2369.,  2432.,  2496.,
        2552.,  2632.,  2687.,  2758.,  2806.,  2854.,  2916.,  2962.,
        3012.,  3079.,  3132.,  3176.,  3221.,  3270.,  3321.,  3364.,
        3430.,  3458.,  3493.,  3527.,  3556.,  3592.,  3622.,  3654.,
        3685.,  3720.,  3751.,  3786.,  3819.,  3847.,  3885.,  3917.,
        3945.,  3976.,  4020.,  4061.,  4097.,  4126.,  4161.,  4192.,
        4224.,  4262.,  4294.,  4330.,  4372.,  4425.,  4493.,  4554.,
        4614.,  4665.,  4736.,  4807.,  4858.,  4928.,  4991.,  5041.,
      

In [41]:
np.save('W_Image_data_per_episode',image)
np.save('W_R_T_data',r_t_data)
np.save('W_Current_pose',Current_pose_euler)
np.save('W_Velocity',velocity)
np.save("W_Episode",Episode)

# Test

In [42]:
import numpy as np

image = np.load("test_image_data_per_episode.npy")

velocity = np.load("test_velocity_data_per_episode.npy")

In [43]:
episode = np.load("test_episode_length.npy")
episode

array([   0,    1,   42,  100,  161,  226,  281,  347,  391,  450,  502,
        560,  634,  708,  780,  853,  902,  956, 1018, 1067, 1120, 1174,
       1218, 1257, 1308, 1352, 1390, 1419, 1448, 1490, 1538, 1577, 1610,
       1650, 1686, 1720, 1754, 1795, 1827, 1858, 1906, 1939, 1974, 2006,
       2035, 2072, 2106, 2139, 2173, 2203, 2234])

In [44]:
image.shape

(2268, 160, 120, 3)

In [45]:
episode.astype(int)

array([   0,    1,   42,  100,  161,  226,  281,  347,  391,  450,  502,
        560,  634,  708,  780,  853,  902,  956, 1018, 1067, 1120, 1174,
       1218, 1257, 1308, 1352, 1390, 1419, 1448, 1490, 1538, 1577, 1610,
       1650, 1686, 1720, 1754, 1795, 1827, 1858, 1906, 1939, 1974, 2006,
       2035, 2072, 2106, 2139, 2173, 2203, 2234])

In [46]:
episode = np.append(episode,2268)

In [47]:
episode = np.delete(episode,0)
episode

array([   1,   42,  100,  161,  226,  281,  347,  391,  450,  502,  560,
        634,  708,  780,  853,  902,  956, 1018, 1067, 1120, 1174, 1218,
       1257, 1308, 1352, 1390, 1419, 1448, 1490, 1538, 1577, 1610, 1650,
       1686, 1720, 1754, 1795, 1827, 1858, 1906, 1939, 1974, 2006, 2035,
       2072, 2106, 2139, 2173, 2203, 2234, 2268])

In [48]:
Episode = np.delete(episode,0)
Episode

array([  42,  100,  161,  226,  281,  347,  391,  450,  502,  560,  634,
        708,  780,  853,  902,  956, 1018, 1067, 1120, 1174, 1218, 1257,
       1308, 1352, 1390, 1419, 1448, 1490, 1538, 1577, 1610, 1650, 1686,
       1720, 1754, 1795, 1827, 1858, 1906, 1939, 1974, 2006, 2035, 2072,
       2106, 2139, 2173, 2203, 2234, 2268])

In [49]:
Episode.shape

(50,)

In [50]:
np.array_equal(image[2], np.zeros([160,120,3]))

False

In [51]:
element_to_delete = [0,1]

In [52]:
image = np.delete(image,element_to_delete,axis=0)
velocity = np.delete(velocity,element_to_delete,axis=0)

In [53]:
element_to_add_1 = -1*np.ones([50,])
element_to_add = [element_to_add_1,element_to_add_1]

In [54]:
for element_to in element_to_add:
    Episode = np.add(Episode,element_to)

In [55]:
Episode

array([  40.,   98.,  159.,  224.,  279.,  345.,  389.,  448.,  500.,
        558.,  632.,  706.,  778.,  851.,  900.,  954., 1016., 1065.,
       1118., 1172., 1216., 1255., 1306., 1350., 1388., 1417., 1446.,
       1488., 1536., 1575., 1608., 1648., 1684., 1718., 1752., 1793.,
       1825., 1856., 1904., 1937., 1972., 2004., 2033., 2070., 2104.,
       2137., 2171., 2201., 2232., 2266.])

In [56]:
image.shape

(2266, 160, 120, 3)

In [58]:
for i in range(2266):
    if np.array_equal(image[i], np.zeros([160,120,3])):
        print(i)

In [59]:
current_pose = np.load('test_current_pose_per_episode.npy')
current_pose

array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[ 3.63288177e-04,  1.07175232e-03, -1.00715829e-03, ...,
          1.58896593e-03,  3.29520231e-03,  9.99993308e-01]],

       ...,

       [[ 1.75258128e+00,  4.17781782e+00, -1.00789915e-03, ...,
         -7.15421976e-04, -8.93405385e-01, -4.49248578e-01]],

       [[ 1.75253173e+00,  4.17787407e+00, -1.00928505e-03, ...,
         -7.19183760e-04, -8.93716682e-01, -4.48628960e-01]],

       [[ 1.75253783e+00,  4.17785476e+00, -1.00925865e-03, ...,
         -7.18308390e-04, -8.93934498e-01, -4.48194785e-01]]])

In [61]:
for i in range(2266):
    if np.array_equal(current_pose[i] , np.array([[0., 0., 0.,0.,0.,0.,0.]])):
        print(i)

0
1


In [62]:
Current_pose = np.delete(current_pose,element_to_delete,axis = 0)

In [63]:
from math import atan
def r_t(pose1,pose2):
    
    theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]
    
    if np.isnan(theta):
        theta = 0
    
    R = ((pose2[1]-pose1[1])**2 + (pose2[0]-pose1[0])**2)**0.5
    
    return [R,theta]

In [64]:
import numpy as np
import math
from scipy.spatial.transform import Rotation as R

def quaternion_to_euler(quaternion):
    r = R.from_quat(quaternion)
    euler = r.as_euler('xyz', degrees=True)
    return euler

# Extracting the quaternion orientations (last 4 elements in each row)
quaternions = Current_pose[:, 0, 3:]

# Converting quaternions to Euler angles
euler_angles = []
for quaternion in quaternions:
    euler_angles.append(quaternion_to_euler(quaternion))

# Converting the list to a NumPy array
euler_angles = np.array(euler_angles)
positions = Current_pose[:, 0, :3]

# Now you have the Euler angles for each timestamp in the "euler_angles_array" variable.
# The shape of euler_angles_array should be (22229, 3) where the three columns represent roll, pitch, and yaw angles in degrees respectively.


In [65]:
Current_pose_euler = np.reshape(np.array([positions[:,0],positions[:,1],euler_angles[:,2]]),[2266, 3])
Current_pose_euler = Current_pose_euler.reshape(2266, 1, 3)

In [66]:
def episode_lengths(parameters):
    lengths = []
    prev_end = 0
    for end in parameters:
        length = end - prev_end
        lengths.append(length)
        prev_end = end
    return lengths


episode_lengths = episode_lengths(Episode)
r_t_data = []
for last,length in zip(Episode,episode_lengths):
    for i in range(int(length)):
        #print(f'{last - length + i+1} ==> {last} $$ {Current_pose[int(last - length + i+1 - 1)][0]} - {Current_pose[int(last)-1][0]} ==> {r_t(Current_pose[int(last - length + i+1 - 1)][0],Current_pose[int(last)-1][0])}')
        r_t_data.append(r_t(Current_pose_euler[int(last - length + i+1 - 1)][0],Current_pose_euler[int(last)-1][0]))

/tmp/ipykernel_13963/163088402.py:4: RuntimeWarning: invalid value encountered in double_scalars
  theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]


In [67]:
r_t_data = np.array(r_t_data)

In [68]:
r_t_data[1]

array([1.91254381, 0.73633138])

In [69]:
def r_tc(pose1,pose2):
    
    theta = atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])) - pose1[2]
    print(f'{(pose2[1]-pose1[1])}/{(pose2[0]-pose1[0])}')
    print(atan((pose2[1]-pose1[1])/(pose2[0]-pose1[0])))
    
    if np.isnan(theta):
        theta = 0
    
    R = ((pose2[1]-pose1[1])**2 + (pose2[0]-pose1[0])**2)**0.5
    
    return [R,theta]

r_tc(Current_pose[127-1][0],Current_pose[136-1][0])

0.0640107172973775/0.11190095178883319
0.5195994880920359


[0.12891545656038128, 0.5206090590404023]

In [71]:
print(Current_pose_euler.shape)
print(image.shape)
print(velocity.shape)
print(r_t_data.shape)
Episode

(2266, 1, 3)
(2266, 160, 120, 3)
(2266, 2, 3)
(2266, 2)


array([  40.,   98.,  159.,  224.,  279.,  345.,  389.,  448.,  500.,
        558.,  632.,  706.,  778.,  851.,  900.,  954., 1016., 1065.,
       1118., 1172., 1216., 1255., 1306., 1350., 1388., 1417., 1446.,
       1488., 1536., 1575., 1608., 1648., 1684., 1718., 1752., 1793.,
       1825., 1856., 1904., 1937., 1972., 2004., 2033., 2070., 2104.,
       2137., 2171., 2201., 2232., 2266.])

In [72]:
np.save('W_test_Image_data_per_episode',image)
np.save('W_test_R_T_data',r_t_data)
np.save('W_teest_Current_pose',Current_pose_euler)
np.save('W_test_Velocity',velocity)
np.save("W_test_Episode",Episode)